/// <reference types="vitest/config" />
import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  plugins: [
    // The router plugin must run before the React plugin.
    tanstackRouter({
      target: "react",
      autoCodeSplitting: true,
    }),
    react(),
    tailwindcss(),
    // PWA shell: makes the app installable so Android registers it as a share target
    // (Web Share Target API). The service worker is generated by Workbox; the manifest's
    // `share_target` POSTs a shared URL/title/text to `/quick-add`, where our custom
    // `share-target-sw.js` (imported into the generated SW) intercepts it, saves to the Inbox,
    // and fires a notification — so an Android share never has to open the app UI.
    VitePWA({
      registerType: "autoUpdate",
      injectRegister: "auto",
      includeAssets: ["favicon.svg", "apple-touch-icon.png"],
      workbox: {
        // The icon registry chunk bundles the full Lucide + Phosphor icon sets (the icon
        // picker exposes every icon), so it exceeds Workbox's default 2 MiB precache limit.
        // Lift the cap so the chunk is still precached for offline use. Keep an eye on this
        // if the icon libraries grow further.
        maximumFileSizeToCacheInBytes: 8 * 1024 * 1024,
        // SPA navigation fallback, but never shadow the gateway's API/docs/storybook routes.
        navigateFallback: "/index.html",
        navigateFallbackDenylist: [/^\/api/, /^\/docs/, /^\/storybook/],
        // Layer our share-target POST handler onto the generated SW. The `?v=` is part of the
        // generated sw.js bytes, so bumping it forces the SW (and the re-imported script) to
        // update — editing share-target-sw.js alone would otherwise be missed. Bump on change.
        importScripts: ["/share-target-sw.js?v=2"],
      },
      manifest: {
        name: "eeSimple Bookmarks",
        short_name: "Bookmarks",
        description: "Save and organize bookmarks.",
        start_url: "/",
        display: "standalone",
        background_color: "#0f172a",
        theme_color: "#0f172a",
        icons: [
          {
            src: "pwa-192x192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "pwa-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "maskable-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        // Registers the app in Android's share sheet. The share POSTs (multipart) to
        // `/quick-add`; `share-target-sw.js` intercepts the POST in the service worker, saves
        // the link to the Inbox, and shows a notification instead of opening the app. (The
        // bookmarklet still GETs `/quick-add?url=…`, which the React route handles as before —
        // the SW only claims the POST, so the two consumers no longer collide.)
        share_target: {
          action: "/quick-add",
          method: "POST",
          enctype: "multipart/form-data",
          params: {
            title: "title",
            text: "text",
            url: "url",
          },
        },
      },
    }),
  ],
  server: {
    port: 5173,
    proxy: {
      "/api": "http://localhost:3001",
    },
  },
  test: {
    environment: "jsdom",
    globals: true,
    css: true,
    setupFiles: ["./src/test-utils/setup.ts"],
  },
});
