/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks.index'
import { Route as SettingsWebsitesRouteImport } from './routes/settings.websites'
import { Route as SettingsTagsRouteImport } from './routes/settings.tags'
import { Route as SettingsDisplayRouteImport } from './routes/settings.display'
import { Route as SettingsCustomPropertiesRouteImport } from './routes/settings.custom-properties'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'
import { Route as SettingsAutomationsRouteImport } from './routes/settings.automations'
import { Route as SettingsAutofillRouteImport } from './routes/settings.autofill'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories.$categorySlug'
import { Route as BookmarksBookmarkIdRouteImport } from './routes/bookmarks.$bookmarkId'
import { Route as SettingsAutofillIndexRouteImport } from './routes/settings.autofill.index'
import { Route as CategoriesCategorySlugIndexRouteImport } from './routes/categories.$categorySlug.index'
import { Route as BookmarksBookmarkIdIndexRouteImport } from './routes/bookmarks.$bookmarkId.index'
import { Route as SettingsAutofillRuleIdRouteImport } from './routes/settings.autofill.$ruleId'
import { Route as CategoriesCategorySlugEditRouteImport } from './routes/categories.$categorySlug.edit'
import { Route as BookmarksBookmarkIdEditRouteImport } from './routes/bookmarks.$bookmarkId.edit'
import { Route as CategoriesCategorySlugEditIndexRouteImport } from './routes/categories.$categorySlug.edit.index'
import { Route as CategoriesCategorySlugEditTieredTagsRouteImport } from './routes/categories.$categorySlug.edit.tiered-tags'
import { Route as CategoriesCategorySlugEditGeneralRouteImport } from './routes/categories.$categorySlug.edit.general'
import { Route as CategoriesCategorySlugEditCustomPropertiesRouteImport } from './routes/categories.$categorySlug.edit.custom-properties'
import { Route as CategoriesCategorySlugEditAutofillRouteImport } from './routes/categories.$categorySlug.edit.autofill'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookmarksRoute,
} as any)
const SettingsWebsitesRoute = SettingsWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomPropertiesRoute =
  SettingsCustomPropertiesRouteImport.update({
    id: '/custom-properties',
    path: '/custom-properties',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationsRoute = SettingsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutofillRoute = SettingsAutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => SettingsRoute,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksBookmarkIdRoute = BookmarksBookmarkIdRouteImport.update({
  id: '/$bookmarkId',
  path: '/$bookmarkId',
  getParentRoute: () => BookmarksRoute,
} as any)
const SettingsAutofillIndexRoute = SettingsAutofillIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsAutofillRoute,
} as any)
const CategoriesCategorySlugIndexRoute =
  CategoriesCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoriesCategorySlugRoute,
  } as any)
const BookmarksBookmarkIdIndexRoute =
  BookmarksBookmarkIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookmarksBookmarkIdRoute,
  } as any)
const SettingsAutofillRuleIdRoute = SettingsAutofillRuleIdRouteImport.update({
  id: '/$ruleId',
  path: '/$ruleId',
  getParentRoute: () => SettingsAutofillRoute,
} as any)
const CategoriesCategorySlugEditRoute =
  CategoriesCategorySlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CategoriesCategorySlugRoute,
  } as any)
const BookmarksBookmarkIdEditRoute = BookmarksBookmarkIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BookmarksBookmarkIdRoute,
} as any)
const CategoriesCategorySlugEditIndexRoute =
  CategoriesCategorySlugEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditTieredTagsRoute =
  CategoriesCategorySlugEditTieredTagsRouteImport.update({
    id: '/tiered-tags',
    path: '/tiered-tags',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditGeneralRoute =
  CategoriesCategorySlugEditGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditCustomPropertiesRoute =
  CategoriesCategorySlugEditCustomPropertiesRouteImport.update({
    id: '/custom-properties',
    path: '/custom-properties',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditAutofillRoute =
  CategoriesCategorySlugEditAutofillRouteImport.update({
    id: '/autofill',
    path: '/autofill',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRouteWithChildren
  '/settings/autofill': typeof SettingsAutofillRouteWithChildren
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditRouteWithChildren
  '/settings/autofill/$ruleId': typeof SettingsAutofillRuleIdRoute
  '/bookmarks/$bookmarkId/': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill/': typeof SettingsAutofillIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/categories/$categorySlug/edit/': typeof CategoriesCategorySlugEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/settings/autofill/$ruleId': typeof SettingsAutofillRuleIdRoute
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill': typeof SettingsAutofillIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRouteWithChildren
  '/settings/autofill': typeof SettingsAutofillRouteWithChildren
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditRouteWithChildren
  '/settings/autofill/$ruleId': typeof SettingsAutofillRuleIdRoute
  '/bookmarks/$bookmarkId/': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill/': typeof SettingsAutofillIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/categories/$categorySlug/edit/': typeof CategoriesCategorySlugEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/settings'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/custom-properties'
    | '/settings/display'
    | '/settings/tags'
    | '/settings/websites'
    | '/bookmarks/'
    | '/settings/'
    | '/bookmarks/$bookmarkId/edit'
    | '/categories/$categorySlug/edit'
    | '/settings/autofill/$ruleId'
    | '/bookmarks/$bookmarkId/'
    | '/categories/$categorySlug/'
    | '/settings/autofill/'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/categories/$categorySlug/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/custom-properties'
    | '/settings/display'
    | '/settings/tags'
    | '/settings/websites'
    | '/bookmarks'
    | '/settings'
    | '/bookmarks/$bookmarkId/edit'
    | '/settings/autofill/$ruleId'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/categories/$categorySlug/edit'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/settings'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/custom-properties'
    | '/settings/display'
    | '/settings/tags'
    | '/settings/websites'
    | '/bookmarks/'
    | '/settings/'
    | '/bookmarks/$bookmarkId/edit'
    | '/categories/$categorySlug/edit'
    | '/settings/autofill/$ruleId'
    | '/bookmarks/$bookmarkId/'
    | '/categories/$categorySlug/'
    | '/settings/autofill/'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/categories/$categorySlug/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/settings/websites': {
      id: '/settings/websites'
      path: '/websites'
      fullPath: '/settings/websites'
      preLoaderRoute: typeof SettingsWebsitesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/custom-properties': {
      id: '/settings/custom-properties'
      path: '/custom-properties'
      fullPath: '/settings/custom-properties'
      preLoaderRoute: typeof SettingsCustomPropertiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automations': {
      id: '/settings/automations'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof SettingsAutomationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/autofill': {
      id: '/settings/autofill'
      path: '/autofill'
      fullPath: '/settings/autofill'
      preLoaderRoute: typeof SettingsAutofillRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$bookmarkId': {
      id: '/bookmarks/$bookmarkId'
      path: '/$bookmarkId'
      fullPath: '/bookmarks/$bookmarkId'
      preLoaderRoute: typeof BookmarksBookmarkIdRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/settings/autofill/': {
      id: '/settings/autofill/'
      path: '/'
      fullPath: '/settings/autofill/'
      preLoaderRoute: typeof SettingsAutofillIndexRouteImport
      parentRoute: typeof SettingsAutofillRoute
    }
    '/categories/$categorySlug/': {
      id: '/categories/$categorySlug/'
      path: '/'
      fullPath: '/categories/$categorySlug/'
      preLoaderRoute: typeof CategoriesCategorySlugIndexRouteImport
      parentRoute: typeof CategoriesCategorySlugRoute
    }
    '/bookmarks/$bookmarkId/': {
      id: '/bookmarks/$bookmarkId/'
      path: '/'
      fullPath: '/bookmarks/$bookmarkId/'
      preLoaderRoute: typeof BookmarksBookmarkIdIndexRouteImport
      parentRoute: typeof BookmarksBookmarkIdRoute
    }
    '/settings/autofill/$ruleId': {
      id: '/settings/autofill/$ruleId'
      path: '/$ruleId'
      fullPath: '/settings/autofill/$ruleId'
      preLoaderRoute: typeof SettingsAutofillRuleIdRouteImport
      parentRoute: typeof SettingsAutofillRoute
    }
    '/categories/$categorySlug/edit': {
      id: '/categories/$categorySlug/edit'
      path: '/edit'
      fullPath: '/categories/$categorySlug/edit'
      preLoaderRoute: typeof CategoriesCategorySlugEditRouteImport
      parentRoute: typeof CategoriesCategorySlugRoute
    }
    '/bookmarks/$bookmarkId/edit': {
      id: '/bookmarks/$bookmarkId/edit'
      path: '/edit'
      fullPath: '/bookmarks/$bookmarkId/edit'
      preLoaderRoute: typeof BookmarksBookmarkIdEditRouteImport
      parentRoute: typeof BookmarksBookmarkIdRoute
    }
    '/categories/$categorySlug/edit/': {
      id: '/categories/$categorySlug/edit/'
      path: '/'
      fullPath: '/categories/$categorySlug/edit/'
      preLoaderRoute: typeof CategoriesCategorySlugEditIndexRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/tiered-tags': {
      id: '/categories/$categorySlug/edit/tiered-tags'
      path: '/tiered-tags'
      fullPath: '/categories/$categorySlug/edit/tiered-tags'
      preLoaderRoute: typeof CategoriesCategorySlugEditTieredTagsRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/general': {
      id: '/categories/$categorySlug/edit/general'
      path: '/general'
      fullPath: '/categories/$categorySlug/edit/general'
      preLoaderRoute: typeof CategoriesCategorySlugEditGeneralRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/custom-properties': {
      id: '/categories/$categorySlug/edit/custom-properties'
      path: '/custom-properties'
      fullPath: '/categories/$categorySlug/edit/custom-properties'
      preLoaderRoute: typeof CategoriesCategorySlugEditCustomPropertiesRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/autofill': {
      id: '/categories/$categorySlug/edit/autofill'
      path: '/autofill'
      fullPath: '/categories/$categorySlug/edit/autofill'
      preLoaderRoute: typeof CategoriesCategorySlugEditAutofillRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
  }
}

interface BookmarksBookmarkIdRouteChildren {
  BookmarksBookmarkIdEditRoute: typeof BookmarksBookmarkIdEditRoute
  BookmarksBookmarkIdIndexRoute: typeof BookmarksBookmarkIdIndexRoute
}

const BookmarksBookmarkIdRouteChildren: BookmarksBookmarkIdRouteChildren = {
  BookmarksBookmarkIdEditRoute: BookmarksBookmarkIdEditRoute,
  BookmarksBookmarkIdIndexRoute: BookmarksBookmarkIdIndexRoute,
}

const BookmarksBookmarkIdRouteWithChildren =
  BookmarksBookmarkIdRoute._addFileChildren(BookmarksBookmarkIdRouteChildren)

interface BookmarksRouteChildren {
  BookmarksBookmarkIdRoute: typeof BookmarksBookmarkIdRouteWithChildren
  BookmarksIndexRoute: typeof BookmarksIndexRoute
}

const BookmarksRouteChildren: BookmarksRouteChildren = {
  BookmarksBookmarkIdRoute: BookmarksBookmarkIdRouteWithChildren,
  BookmarksIndexRoute: BookmarksIndexRoute,
}

const BookmarksRouteWithChildren = BookmarksRoute._addFileChildren(
  BookmarksRouteChildren,
)

interface SettingsAutofillRouteChildren {
  SettingsAutofillRuleIdRoute: typeof SettingsAutofillRuleIdRoute
  SettingsAutofillIndexRoute: typeof SettingsAutofillIndexRoute
}

const SettingsAutofillRouteChildren: SettingsAutofillRouteChildren = {
  SettingsAutofillRuleIdRoute: SettingsAutofillRuleIdRoute,
  SettingsAutofillIndexRoute: SettingsAutofillIndexRoute,
}

const SettingsAutofillRouteWithChildren =
  SettingsAutofillRoute._addFileChildren(SettingsAutofillRouteChildren)

interface SettingsRouteChildren {
  SettingsAutofillRoute: typeof SettingsAutofillRouteWithChildren
  SettingsAutomationsRoute: typeof SettingsAutomationsRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsCustomPropertiesRoute: typeof SettingsCustomPropertiesRoute
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
  SettingsWebsitesRoute: typeof SettingsWebsitesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAutofillRoute: SettingsAutofillRouteWithChildren,
  SettingsAutomationsRoute: SettingsAutomationsRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsCustomPropertiesRoute: SettingsCustomPropertiesRoute,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsTagsRoute: SettingsTagsRoute,
  SettingsWebsitesRoute: SettingsWebsitesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface CategoriesCategorySlugEditRouteChildren {
  CategoriesCategorySlugEditAutofillRoute: typeof CategoriesCategorySlugEditAutofillRoute
  CategoriesCategorySlugEditCustomPropertiesRoute: typeof CategoriesCategorySlugEditCustomPropertiesRoute
  CategoriesCategorySlugEditGeneralRoute: typeof CategoriesCategorySlugEditGeneralRoute
  CategoriesCategorySlugEditTieredTagsRoute: typeof CategoriesCategorySlugEditTieredTagsRoute
  CategoriesCategorySlugEditIndexRoute: typeof CategoriesCategorySlugEditIndexRoute
}

const CategoriesCategorySlugEditRouteChildren: CategoriesCategorySlugEditRouteChildren =
  {
    CategoriesCategorySlugEditAutofillRoute:
      CategoriesCategorySlugEditAutofillRoute,
    CategoriesCategorySlugEditCustomPropertiesRoute:
      CategoriesCategorySlugEditCustomPropertiesRoute,
    CategoriesCategorySlugEditGeneralRoute:
      CategoriesCategorySlugEditGeneralRoute,
    CategoriesCategorySlugEditTieredTagsRoute:
      CategoriesCategorySlugEditTieredTagsRoute,
    CategoriesCategorySlugEditIndexRoute: CategoriesCategorySlugEditIndexRoute,
  }

const CategoriesCategorySlugEditRouteWithChildren =
  CategoriesCategorySlugEditRoute._addFileChildren(
    CategoriesCategorySlugEditRouteChildren,
  )

interface CategoriesCategorySlugRouteChildren {
  CategoriesCategorySlugEditRoute: typeof CategoriesCategorySlugEditRouteWithChildren
  CategoriesCategorySlugIndexRoute: typeof CategoriesCategorySlugIndexRoute
}

const CategoriesCategorySlugRouteChildren: CategoriesCategorySlugRouteChildren =
  {
    CategoriesCategorySlugEditRoute:
      CategoriesCategorySlugEditRouteWithChildren,
    CategoriesCategorySlugIndexRoute: CategoriesCategorySlugIndexRoute,
  }

const CategoriesCategorySlugRouteWithChildren =
  CategoriesCategorySlugRoute._addFileChildren(
    CategoriesCategorySlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
