/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomPropertiesRouteImport } from './routes/custom-properties'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AutofillRouteImport } from './routes/autofill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CustomPropertiesIndexRouteImport } from './routes/custom-properties.index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks.index'
import { Route as AutofillIndexRouteImport } from './routes/autofill.index'
import { Route as TaxonomiesYoutubeChannelsRouteImport } from './routes/taxonomies.youtube-channels'
import { Route as TaxonomiesWebsitesRouteImport } from './routes/taxonomies.websites'
import { Route as TaxonomiesTagsRouteImport } from './routes/taxonomies.tags'
import { Route as TaxonomiesMediaTypesRouteImport } from './routes/taxonomies.media-types'
import { Route as SettingsYoutubeChannelsRouteImport } from './routes/settings.youtube-channels'
import { Route as SettingsWebsitesRouteImport } from './routes/settings.websites'
import { Route as SettingsTagsRouteImport } from './routes/settings.tags'
import { Route as SettingsMediaTypesRouteImport } from './routes/settings.media-types'
import { Route as SettingsHomepageRouteImport } from './routes/settings.homepage'
import { Route as SettingsDisplayRouteImport } from './routes/settings.display'
import { Route as SettingsCustomPropertiesRouteImport } from './routes/settings.custom-properties'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'
import { Route as SettingsAutomationsRouteImport } from './routes/settings.automations'
import { Route as SettingsAutofillRouteImport } from './routes/settings.autofill'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories.$categorySlug'
import { Route as BookmarksBookmarkIdRouteImport } from './routes/bookmarks.$bookmarkId'
import { Route as TaxonomiesYoutubeChannelsIndexRouteImport } from './routes/taxonomies.youtube-channels.index'
import { Route as TaxonomiesWebsitesIndexRouteImport } from './routes/taxonomies.websites.index'
import { Route as TaxonomiesMediaTypesIndexRouteImport } from './routes/taxonomies.media-types.index'
import { Route as SettingsCustomPropertiesIndexRouteImport } from './routes/settings.custom-properties.index'
import { Route as SettingsAutofillIndexRouteImport } from './routes/settings.autofill.index'
import { Route as CategoriesCategorySlugIndexRouteImport } from './routes/categories.$categorySlug.index'
import { Route as BookmarksBookmarkIdIndexRouteImport } from './routes/bookmarks.$bookmarkId.index'
import { Route as TaxonomiesYoutubeChannelsChannelSlugRouteImport } from './routes/taxonomies.youtube-channels.$channelSlug'
import { Route as TaxonomiesWebsitesWebsiteSlugRouteImport } from './routes/taxonomies.websites.$websiteSlug'
import { Route as TaxonomiesMediaTypesMediaTypeSlugRouteImport } from './routes/taxonomies.media-types.$mediaTypeSlug'
import { Route as SettingsCustomPropertiesNewRouteImport } from './routes/settings.custom-properties.new'
import { Route as SettingsCustomPropertiesPropertySlugRouteImport } from './routes/settings.custom-properties.$propertySlug'
import { Route as SettingsAutofillRuleSlugRouteImport } from './routes/settings.autofill.$ruleSlug'
import { Route as CategoriesCategorySlugEditRouteImport } from './routes/categories.$categorySlug.edit'
import { Route as BookmarksBookmarkIdEditRouteImport } from './routes/bookmarks.$bookmarkId.edit'
import { Route as TaxonomiesYoutubeChannelsChannelSlugIndexRouteImport } from './routes/taxonomies.youtube-channels.$channelSlug.index'
import { Route as TaxonomiesWebsitesWebsiteSlugIndexRouteImport } from './routes/taxonomies.websites.$websiteSlug.index'
import { Route as TaxonomiesMediaTypesMediaTypeSlugIndexRouteImport } from './routes/taxonomies.media-types.$mediaTypeSlug.index'
import { Route as SettingsCustomPropertiesPropertySlugIndexRouteImport } from './routes/settings.custom-properties.$propertySlug.index'
import { Route as SettingsAutofillRuleSlugIndexRouteImport } from './routes/settings.autofill.$ruleSlug.index'
import { Route as CategoriesCategorySlugEditIndexRouteImport } from './routes/categories.$categorySlug.edit.index'
import { Route as TaxonomiesYoutubeChannelsChannelSlugEditRouteImport } from './routes/taxonomies.youtube-channels.$channelSlug.edit'
import { Route as TaxonomiesWebsitesWebsiteSlugEditRouteImport } from './routes/taxonomies.websites.$websiteSlug.edit'
import { Route as TaxonomiesMediaTypesMediaTypeSlugEditRouteImport } from './routes/taxonomies.media-types.$mediaTypeSlug.edit'
import { Route as SettingsCustomPropertiesPropertySlugEditRouteImport } from './routes/settings.custom-properties.$propertySlug.edit'
import { Route as SettingsAutofillRuleSlugEditRouteImport } from './routes/settings.autofill.$ruleSlug.edit'
import { Route as CategoriesCategorySlugEditTieredTagsRouteImport } from './routes/categories.$categorySlug.edit.tiered-tags'
import { Route as CategoriesCategorySlugEditGeneralRouteImport } from './routes/categories.$categorySlug.edit.general'
import { Route as CategoriesCategorySlugEditCustomPropertiesRouteImport } from './routes/categories.$categorySlug.edit.custom-properties'
import { Route as CategoriesCategorySlugEditAutofillRouteImport } from './routes/categories.$categorySlug.edit.autofill'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomPropertiesRoute = CustomPropertiesRouteImport.update({
  id: '/custom-properties',
  path: '/custom-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AutofillRoute = AutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CustomPropertiesIndexRoute = CustomPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomPropertiesRoute,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookmarksRoute,
} as any)
const AutofillIndexRoute = AutofillIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutofillRoute,
} as any)
const TaxonomiesYoutubeChannelsRoute =
  TaxonomiesYoutubeChannelsRouteImport.update({
    id: '/taxonomies/youtube-channels',
    path: '/taxonomies/youtube-channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const TaxonomiesWebsitesRoute = TaxonomiesWebsitesRouteImport.update({
  id: '/taxonomies/websites',
  path: '/taxonomies/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomiesTagsRoute = TaxonomiesTagsRouteImport.update({
  id: '/taxonomies/tags',
  path: '/taxonomies/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomiesMediaTypesRoute = TaxonomiesMediaTypesRouteImport.update({
  id: '/taxonomies/media-types',
  path: '/taxonomies/media-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsYoutubeChannelsRoute = SettingsYoutubeChannelsRouteImport.update({
  id: '/youtube-channels',
  path: '/youtube-channels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebsitesRoute = SettingsWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMediaTypesRoute = SettingsMediaTypesRouteImport.update({
  id: '/media-types',
  path: '/media-types',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHomepageRoute = SettingsHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomPropertiesRoute =
  SettingsCustomPropertiesRouteImport.update({
    id: '/custom-properties',
    path: '/custom-properties',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationsRoute = SettingsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutofillRoute = SettingsAutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => SettingsRoute,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksBookmarkIdRoute = BookmarksBookmarkIdRouteImport.update({
  id: '/$bookmarkId',
  path: '/$bookmarkId',
  getParentRoute: () => BookmarksRoute,
} as any)
const TaxonomiesYoutubeChannelsIndexRoute =
  TaxonomiesYoutubeChannelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TaxonomiesYoutubeChannelsRoute,
  } as any)
const TaxonomiesWebsitesIndexRoute = TaxonomiesWebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaxonomiesWebsitesRoute,
} as any)
const TaxonomiesMediaTypesIndexRoute =
  TaxonomiesMediaTypesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TaxonomiesMediaTypesRoute,
  } as any)
const SettingsCustomPropertiesIndexRoute =
  SettingsCustomPropertiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsCustomPropertiesRoute,
  } as any)
const SettingsAutofillIndexRoute = SettingsAutofillIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsAutofillRoute,
} as any)
const CategoriesCategorySlugIndexRoute =
  CategoriesCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoriesCategorySlugRoute,
  } as any)
const BookmarksBookmarkIdIndexRoute =
  BookmarksBookmarkIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookmarksBookmarkIdRoute,
  } as any)
const TaxonomiesYoutubeChannelsChannelSlugRoute =
  TaxonomiesYoutubeChannelsChannelSlugRouteImport.update({
    id: '/$channelSlug',
    path: '/$channelSlug',
    getParentRoute: () => TaxonomiesYoutubeChannelsRoute,
  } as any)
const TaxonomiesWebsitesWebsiteSlugRoute =
  TaxonomiesWebsitesWebsiteSlugRouteImport.update({
    id: '/$websiteSlug',
    path: '/$websiteSlug',
    getParentRoute: () => TaxonomiesWebsitesRoute,
  } as any)
const TaxonomiesMediaTypesMediaTypeSlugRoute =
  TaxonomiesMediaTypesMediaTypeSlugRouteImport.update({
    id: '/$mediaTypeSlug',
    path: '/$mediaTypeSlug',
    getParentRoute: () => TaxonomiesMediaTypesRoute,
  } as any)
const SettingsCustomPropertiesNewRoute =
  SettingsCustomPropertiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SettingsCustomPropertiesRoute,
  } as any)
const SettingsCustomPropertiesPropertySlugRoute =
  SettingsCustomPropertiesPropertySlugRouteImport.update({
    id: '/$propertySlug',
    path: '/$propertySlug',
    getParentRoute: () => SettingsCustomPropertiesRoute,
  } as any)
const SettingsAutofillRuleSlugRoute =
  SettingsAutofillRuleSlugRouteImport.update({
    id: '/$ruleSlug',
    path: '/$ruleSlug',
    getParentRoute: () => SettingsAutofillRoute,
  } as any)
const CategoriesCategorySlugEditRoute =
  CategoriesCategorySlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CategoriesCategorySlugRoute,
  } as any)
const BookmarksBookmarkIdEditRoute = BookmarksBookmarkIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BookmarksBookmarkIdRoute,
} as any)
const TaxonomiesYoutubeChannelsChannelSlugIndexRoute =
  TaxonomiesYoutubeChannelsChannelSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TaxonomiesYoutubeChannelsChannelSlugRoute,
  } as any)
const TaxonomiesWebsitesWebsiteSlugIndexRoute =
  TaxonomiesWebsitesWebsiteSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TaxonomiesWebsitesWebsiteSlugRoute,
  } as any)
const TaxonomiesMediaTypesMediaTypeSlugIndexRoute =
  TaxonomiesMediaTypesMediaTypeSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TaxonomiesMediaTypesMediaTypeSlugRoute,
  } as any)
const SettingsCustomPropertiesPropertySlugIndexRoute =
  SettingsCustomPropertiesPropertySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsCustomPropertiesPropertySlugRoute,
  } as any)
const SettingsAutofillRuleSlugIndexRoute =
  SettingsAutofillRuleSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsAutofillRuleSlugRoute,
  } as any)
const CategoriesCategorySlugEditIndexRoute =
  CategoriesCategorySlugEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const TaxonomiesYoutubeChannelsChannelSlugEditRoute =
  TaxonomiesYoutubeChannelsChannelSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TaxonomiesYoutubeChannelsChannelSlugRoute,
  } as any)
const TaxonomiesWebsitesWebsiteSlugEditRoute =
  TaxonomiesWebsitesWebsiteSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TaxonomiesWebsitesWebsiteSlugRoute,
  } as any)
const TaxonomiesMediaTypesMediaTypeSlugEditRoute =
  TaxonomiesMediaTypesMediaTypeSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TaxonomiesMediaTypesMediaTypeSlugRoute,
  } as any)
const SettingsCustomPropertiesPropertySlugEditRoute =
  SettingsCustomPropertiesPropertySlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SettingsCustomPropertiesPropertySlugRoute,
  } as any)
const SettingsAutofillRuleSlugEditRoute =
  SettingsAutofillRuleSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SettingsAutofillRuleSlugRoute,
  } as any)
const CategoriesCategorySlugEditTieredTagsRoute =
  CategoriesCategorySlugEditTieredTagsRouteImport.update({
    id: '/tiered-tags',
    path: '/tiered-tags',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditGeneralRoute =
  CategoriesCategorySlugEditGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditCustomPropertiesRoute =
  CategoriesCategorySlugEditCustomPropertiesRouteImport.update({
    id: '/custom-properties',
    path: '/custom-properties',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)
const CategoriesCategorySlugEditAutofillRoute =
  CategoriesCategorySlugEditAutofillRouteImport.update({
    id: '/autofill',
    path: '/autofill',
    getParentRoute: () => CategoriesCategorySlugEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autofill': typeof AutofillRouteWithChildren
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/custom-properties': typeof CustomPropertiesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRouteWithChildren
  '/settings/autofill': typeof SettingsAutofillRouteWithChildren
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesRouteWithChildren
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/settings/youtube-channels': typeof SettingsYoutubeChannelsRoute
  '/taxonomies/media-types': typeof TaxonomiesMediaTypesRouteWithChildren
  '/taxonomies/tags': typeof TaxonomiesTagsRoute
  '/taxonomies/websites': typeof TaxonomiesWebsitesRouteWithChildren
  '/taxonomies/youtube-channels': typeof TaxonomiesYoutubeChannelsRouteWithChildren
  '/autofill/': typeof AutofillIndexRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/custom-properties/': typeof CustomPropertiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditRouteWithChildren
  '/settings/autofill/$ruleSlug': typeof SettingsAutofillRuleSlugRouteWithChildren
  '/settings/custom-properties/$propertySlug': typeof SettingsCustomPropertiesPropertySlugRouteWithChildren
  '/settings/custom-properties/new': typeof SettingsCustomPropertiesNewRoute
  '/taxonomies/media-types/$mediaTypeSlug': typeof TaxonomiesMediaTypesMediaTypeSlugRouteWithChildren
  '/taxonomies/websites/$websiteSlug': typeof TaxonomiesWebsitesWebsiteSlugRouteWithChildren
  '/taxonomies/youtube-channels/$channelSlug': typeof TaxonomiesYoutubeChannelsChannelSlugRouteWithChildren
  '/bookmarks/$bookmarkId/': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill/': typeof SettingsAutofillIndexRoute
  '/settings/custom-properties/': typeof SettingsCustomPropertiesIndexRoute
  '/taxonomies/media-types/': typeof TaxonomiesMediaTypesIndexRoute
  '/taxonomies/websites/': typeof TaxonomiesWebsitesIndexRoute
  '/taxonomies/youtube-channels/': typeof TaxonomiesYoutubeChannelsIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/settings/autofill/$ruleSlug/edit': typeof SettingsAutofillRuleSlugEditRoute
  '/settings/custom-properties/$propertySlug/edit': typeof SettingsCustomPropertiesPropertySlugEditRoute
  '/taxonomies/media-types/$mediaTypeSlug/edit': typeof TaxonomiesMediaTypesMediaTypeSlugEditRoute
  '/taxonomies/websites/$websiteSlug/edit': typeof TaxonomiesWebsitesWebsiteSlugEditRoute
  '/taxonomies/youtube-channels/$channelSlug/edit': typeof TaxonomiesYoutubeChannelsChannelSlugEditRoute
  '/categories/$categorySlug/edit/': typeof CategoriesCategorySlugEditIndexRoute
  '/settings/autofill/$ruleSlug/': typeof SettingsAutofillRuleSlugIndexRoute
  '/settings/custom-properties/$propertySlug/': typeof SettingsCustomPropertiesPropertySlugIndexRoute
  '/taxonomies/media-types/$mediaTypeSlug/': typeof TaxonomiesMediaTypesMediaTypeSlugIndexRoute
  '/taxonomies/websites/$websiteSlug/': typeof TaxonomiesWebsitesWebsiteSlugIndexRoute
  '/taxonomies/youtube-channels/$channelSlug/': typeof TaxonomiesYoutubeChannelsChannelSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/settings/youtube-channels': typeof SettingsYoutubeChannelsRoute
  '/taxonomies/tags': typeof TaxonomiesTagsRoute
  '/autofill': typeof AutofillIndexRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/custom-properties': typeof CustomPropertiesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/settings/custom-properties/new': typeof SettingsCustomPropertiesNewRoute
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill': typeof SettingsAutofillIndexRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesIndexRoute
  '/taxonomies/media-types': typeof TaxonomiesMediaTypesIndexRoute
  '/taxonomies/websites': typeof TaxonomiesWebsitesIndexRoute
  '/taxonomies/youtube-channels': typeof TaxonomiesYoutubeChannelsIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/settings/autofill/$ruleSlug/edit': typeof SettingsAutofillRuleSlugEditRoute
  '/settings/custom-properties/$propertySlug/edit': typeof SettingsCustomPropertiesPropertySlugEditRoute
  '/taxonomies/media-types/$mediaTypeSlug/edit': typeof TaxonomiesMediaTypesMediaTypeSlugEditRoute
  '/taxonomies/websites/$websiteSlug/edit': typeof TaxonomiesWebsitesWebsiteSlugEditRoute
  '/taxonomies/youtube-channels/$channelSlug/edit': typeof TaxonomiesYoutubeChannelsChannelSlugEditRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditIndexRoute
  '/settings/autofill/$ruleSlug': typeof SettingsAutofillRuleSlugIndexRoute
  '/settings/custom-properties/$propertySlug': typeof SettingsCustomPropertiesPropertySlugIndexRoute
  '/taxonomies/media-types/$mediaTypeSlug': typeof TaxonomiesMediaTypesMediaTypeSlugIndexRoute
  '/taxonomies/websites/$websiteSlug': typeof TaxonomiesWebsitesWebsiteSlugIndexRoute
  '/taxonomies/youtube-channels/$channelSlug': typeof TaxonomiesYoutubeChannelsChannelSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autofill': typeof AutofillRouteWithChildren
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/custom-properties': typeof CustomPropertiesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/bookmarks/$bookmarkId': typeof BookmarksBookmarkIdRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRouteWithChildren
  '/settings/autofill': typeof SettingsAutofillRouteWithChildren
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/custom-properties': typeof SettingsCustomPropertiesRouteWithChildren
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/homepage': typeof SettingsHomepageRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/websites': typeof SettingsWebsitesRoute
  '/settings/youtube-channels': typeof SettingsYoutubeChannelsRoute
  '/taxonomies/media-types': typeof TaxonomiesMediaTypesRouteWithChildren
  '/taxonomies/tags': typeof TaxonomiesTagsRoute
  '/taxonomies/websites': typeof TaxonomiesWebsitesRouteWithChildren
  '/taxonomies/youtube-channels': typeof TaxonomiesYoutubeChannelsRouteWithChildren
  '/autofill/': typeof AutofillIndexRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/custom-properties/': typeof CustomPropertiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookmarks/$bookmarkId/edit': typeof BookmarksBookmarkIdEditRoute
  '/categories/$categorySlug/edit': typeof CategoriesCategorySlugEditRouteWithChildren
  '/settings/autofill/$ruleSlug': typeof SettingsAutofillRuleSlugRouteWithChildren
  '/settings/custom-properties/$propertySlug': typeof SettingsCustomPropertiesPropertySlugRouteWithChildren
  '/settings/custom-properties/new': typeof SettingsCustomPropertiesNewRoute
  '/taxonomies/media-types/$mediaTypeSlug': typeof TaxonomiesMediaTypesMediaTypeSlugRouteWithChildren
  '/taxonomies/websites/$websiteSlug': typeof TaxonomiesWebsitesWebsiteSlugRouteWithChildren
  '/taxonomies/youtube-channels/$channelSlug': typeof TaxonomiesYoutubeChannelsChannelSlugRouteWithChildren
  '/bookmarks/$bookmarkId/': typeof BookmarksBookmarkIdIndexRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/settings/autofill/': typeof SettingsAutofillIndexRoute
  '/settings/custom-properties/': typeof SettingsCustomPropertiesIndexRoute
  '/taxonomies/media-types/': typeof TaxonomiesMediaTypesIndexRoute
  '/taxonomies/websites/': typeof TaxonomiesWebsitesIndexRoute
  '/taxonomies/youtube-channels/': typeof TaxonomiesYoutubeChannelsIndexRoute
  '/categories/$categorySlug/edit/autofill': typeof CategoriesCategorySlugEditAutofillRoute
  '/categories/$categorySlug/edit/custom-properties': typeof CategoriesCategorySlugEditCustomPropertiesRoute
  '/categories/$categorySlug/edit/general': typeof CategoriesCategorySlugEditGeneralRoute
  '/categories/$categorySlug/edit/tiered-tags': typeof CategoriesCategorySlugEditTieredTagsRoute
  '/settings/autofill/$ruleSlug/edit': typeof SettingsAutofillRuleSlugEditRoute
  '/settings/custom-properties/$propertySlug/edit': typeof SettingsCustomPropertiesPropertySlugEditRoute
  '/taxonomies/media-types/$mediaTypeSlug/edit': typeof TaxonomiesMediaTypesMediaTypeSlugEditRoute
  '/taxonomies/websites/$websiteSlug/edit': typeof TaxonomiesWebsitesWebsiteSlugEditRoute
  '/taxonomies/youtube-channels/$channelSlug/edit': typeof TaxonomiesYoutubeChannelsChannelSlugEditRoute
  '/categories/$categorySlug/edit/': typeof CategoriesCategorySlugEditIndexRoute
  '/settings/autofill/$ruleSlug/': typeof SettingsAutofillRuleSlugIndexRoute
  '/settings/custom-properties/$propertySlug/': typeof SettingsCustomPropertiesPropertySlugIndexRoute
  '/taxonomies/media-types/$mediaTypeSlug/': typeof TaxonomiesMediaTypesMediaTypeSlugIndexRoute
  '/taxonomies/websites/$websiteSlug/': typeof TaxonomiesWebsitesWebsiteSlugIndexRoute
  '/taxonomies/youtube-channels/$channelSlug/': typeof TaxonomiesYoutubeChannelsChannelSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autofill'
    | '/bookmarks'
    | '/custom-properties'
    | '/settings'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/custom-properties'
    | '/settings/display'
    | '/settings/homepage'
    | '/settings/media-types'
    | '/settings/tags'
    | '/settings/websites'
    | '/settings/youtube-channels'
    | '/taxonomies/media-types'
    | '/taxonomies/tags'
    | '/taxonomies/websites'
    | '/taxonomies/youtube-channels'
    | '/autofill/'
    | '/bookmarks/'
    | '/custom-properties/'
    | '/settings/'
    | '/bookmarks/$bookmarkId/edit'
    | '/categories/$categorySlug/edit'
    | '/settings/autofill/$ruleSlug'
    | '/settings/custom-properties/$propertySlug'
    | '/settings/custom-properties/new'
    | '/taxonomies/media-types/$mediaTypeSlug'
    | '/taxonomies/websites/$websiteSlug'
    | '/taxonomies/youtube-channels/$channelSlug'
    | '/bookmarks/$bookmarkId/'
    | '/categories/$categorySlug/'
    | '/settings/autofill/'
    | '/settings/custom-properties/'
    | '/taxonomies/media-types/'
    | '/taxonomies/websites/'
    | '/taxonomies/youtube-channels/'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/settings/autofill/$ruleSlug/edit'
    | '/settings/custom-properties/$propertySlug/edit'
    | '/taxonomies/media-types/$mediaTypeSlug/edit'
    | '/taxonomies/websites/$websiteSlug/edit'
    | '/taxonomies/youtube-channels/$channelSlug/edit'
    | '/categories/$categorySlug/edit/'
    | '/settings/autofill/$ruleSlug/'
    | '/settings/custom-properties/$propertySlug/'
    | '/taxonomies/media-types/$mediaTypeSlug/'
    | '/taxonomies/websites/$websiteSlug/'
    | '/taxonomies/youtube-channels/$channelSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/display'
    | '/settings/homepage'
    | '/settings/media-types'
    | '/settings/tags'
    | '/settings/websites'
    | '/settings/youtube-channels'
    | '/taxonomies/tags'
    | '/autofill'
    | '/bookmarks'
    | '/custom-properties'
    | '/settings'
    | '/bookmarks/$bookmarkId/edit'
    | '/settings/custom-properties/new'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/settings/custom-properties'
    | '/taxonomies/media-types'
    | '/taxonomies/websites'
    | '/taxonomies/youtube-channels'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/settings/autofill/$ruleSlug/edit'
    | '/settings/custom-properties/$propertySlug/edit'
    | '/taxonomies/media-types/$mediaTypeSlug/edit'
    | '/taxonomies/websites/$websiteSlug/edit'
    | '/taxonomies/youtube-channels/$channelSlug/edit'
    | '/categories/$categorySlug/edit'
    | '/settings/autofill/$ruleSlug'
    | '/settings/custom-properties/$propertySlug'
    | '/taxonomies/media-types/$mediaTypeSlug'
    | '/taxonomies/websites/$websiteSlug'
    | '/taxonomies/youtube-channels/$channelSlug'
  id:
    | '__root__'
    | '/'
    | '/autofill'
    | '/bookmarks'
    | '/custom-properties'
    | '/settings'
    | '/bookmarks/$bookmarkId'
    | '/categories/$categorySlug'
    | '/settings/autofill'
    | '/settings/automations'
    | '/settings/categories'
    | '/settings/custom-properties'
    | '/settings/display'
    | '/settings/homepage'
    | '/settings/media-types'
    | '/settings/tags'
    | '/settings/websites'
    | '/settings/youtube-channels'
    | '/taxonomies/media-types'
    | '/taxonomies/tags'
    | '/taxonomies/websites'
    | '/taxonomies/youtube-channels'
    | '/autofill/'
    | '/bookmarks/'
    | '/custom-properties/'
    | '/settings/'
    | '/bookmarks/$bookmarkId/edit'
    | '/categories/$categorySlug/edit'
    | '/settings/autofill/$ruleSlug'
    | '/settings/custom-properties/$propertySlug'
    | '/settings/custom-properties/new'
    | '/taxonomies/media-types/$mediaTypeSlug'
    | '/taxonomies/websites/$websiteSlug'
    | '/taxonomies/youtube-channels/$channelSlug'
    | '/bookmarks/$bookmarkId/'
    | '/categories/$categorySlug/'
    | '/settings/autofill/'
    | '/settings/custom-properties/'
    | '/taxonomies/media-types/'
    | '/taxonomies/websites/'
    | '/taxonomies/youtube-channels/'
    | '/categories/$categorySlug/edit/autofill'
    | '/categories/$categorySlug/edit/custom-properties'
    | '/categories/$categorySlug/edit/general'
    | '/categories/$categorySlug/edit/tiered-tags'
    | '/settings/autofill/$ruleSlug/edit'
    | '/settings/custom-properties/$propertySlug/edit'
    | '/taxonomies/media-types/$mediaTypeSlug/edit'
    | '/taxonomies/websites/$websiteSlug/edit'
    | '/taxonomies/youtube-channels/$channelSlug/edit'
    | '/categories/$categorySlug/edit/'
    | '/settings/autofill/$ruleSlug/'
    | '/settings/custom-properties/$propertySlug/'
    | '/taxonomies/media-types/$mediaTypeSlug/'
    | '/taxonomies/websites/$websiteSlug/'
    | '/taxonomies/youtube-channels/$channelSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutofillRoute: typeof AutofillRouteWithChildren
  BookmarksRoute: typeof BookmarksRouteWithChildren
  CustomPropertiesRoute: typeof CustomPropertiesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRouteWithChildren
  TaxonomiesMediaTypesRoute: typeof TaxonomiesMediaTypesRouteWithChildren
  TaxonomiesTagsRoute: typeof TaxonomiesTagsRoute
  TaxonomiesWebsitesRoute: typeof TaxonomiesWebsitesRouteWithChildren
  TaxonomiesYoutubeChannelsRoute: typeof TaxonomiesYoutubeChannelsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-properties': {
      id: '/custom-properties'
      path: '/custom-properties'
      fullPath: '/custom-properties'
      preLoaderRoute: typeof CustomPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autofill': {
      id: '/autofill'
      path: '/autofill'
      fullPath: '/autofill'
      preLoaderRoute: typeof AutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/custom-properties/': {
      id: '/custom-properties/'
      path: '/'
      fullPath: '/custom-properties/'
      preLoaderRoute: typeof CustomPropertiesIndexRouteImport
      parentRoute: typeof CustomPropertiesRoute
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/autofill/': {
      id: '/autofill/'
      path: '/'
      fullPath: '/autofill/'
      preLoaderRoute: typeof AutofillIndexRouteImport
      parentRoute: typeof AutofillRoute
    }
    '/taxonomies/youtube-channels': {
      id: '/taxonomies/youtube-channels'
      path: '/taxonomies/youtube-channels'
      fullPath: '/taxonomies/youtube-channels'
      preLoaderRoute: typeof TaxonomiesYoutubeChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomies/websites': {
      id: '/taxonomies/websites'
      path: '/taxonomies/websites'
      fullPath: '/taxonomies/websites'
      preLoaderRoute: typeof TaxonomiesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomies/tags': {
      id: '/taxonomies/tags'
      path: '/taxonomies/tags'
      fullPath: '/taxonomies/tags'
      preLoaderRoute: typeof TaxonomiesTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomies/media-types': {
      id: '/taxonomies/media-types'
      path: '/taxonomies/media-types'
      fullPath: '/taxonomies/media-types'
      preLoaderRoute: typeof TaxonomiesMediaTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/youtube-channels': {
      id: '/settings/youtube-channels'
      path: '/youtube-channels'
      fullPath: '/settings/youtube-channels'
      preLoaderRoute: typeof SettingsYoutubeChannelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/websites': {
      id: '/settings/websites'
      path: '/websites'
      fullPath: '/settings/websites'
      preLoaderRoute: typeof SettingsWebsitesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/media-types': {
      id: '/settings/media-types'
      path: '/media-types'
      fullPath: '/settings/media-types'
      preLoaderRoute: typeof SettingsMediaTypesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/homepage': {
      id: '/settings/homepage'
      path: '/homepage'
      fullPath: '/settings/homepage'
      preLoaderRoute: typeof SettingsHomepageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/custom-properties': {
      id: '/settings/custom-properties'
      path: '/custom-properties'
      fullPath: '/settings/custom-properties'
      preLoaderRoute: typeof SettingsCustomPropertiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automations': {
      id: '/settings/automations'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof SettingsAutomationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/autofill': {
      id: '/settings/autofill'
      path: '/autofill'
      fullPath: '/settings/autofill'
      preLoaderRoute: typeof SettingsAutofillRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$bookmarkId': {
      id: '/bookmarks/$bookmarkId'
      path: '/$bookmarkId'
      fullPath: '/bookmarks/$bookmarkId'
      preLoaderRoute: typeof BookmarksBookmarkIdRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/taxonomies/youtube-channels/': {
      id: '/taxonomies/youtube-channels/'
      path: '/'
      fullPath: '/taxonomies/youtube-channels/'
      preLoaderRoute: typeof TaxonomiesYoutubeChannelsIndexRouteImport
      parentRoute: typeof TaxonomiesYoutubeChannelsRoute
    }
    '/taxonomies/websites/': {
      id: '/taxonomies/websites/'
      path: '/'
      fullPath: '/taxonomies/websites/'
      preLoaderRoute: typeof TaxonomiesWebsitesIndexRouteImport
      parentRoute: typeof TaxonomiesWebsitesRoute
    }
    '/taxonomies/media-types/': {
      id: '/taxonomies/media-types/'
      path: '/'
      fullPath: '/taxonomies/media-types/'
      preLoaderRoute: typeof TaxonomiesMediaTypesIndexRouteImport
      parentRoute: typeof TaxonomiesMediaTypesRoute
    }
    '/settings/custom-properties/': {
      id: '/settings/custom-properties/'
      path: '/'
      fullPath: '/settings/custom-properties/'
      preLoaderRoute: typeof SettingsCustomPropertiesIndexRouteImport
      parentRoute: typeof SettingsCustomPropertiesRoute
    }
    '/settings/autofill/': {
      id: '/settings/autofill/'
      path: '/'
      fullPath: '/settings/autofill/'
      preLoaderRoute: typeof SettingsAutofillIndexRouteImport
      parentRoute: typeof SettingsAutofillRoute
    }
    '/categories/$categorySlug/': {
      id: '/categories/$categorySlug/'
      path: '/'
      fullPath: '/categories/$categorySlug/'
      preLoaderRoute: typeof CategoriesCategorySlugIndexRouteImport
      parentRoute: typeof CategoriesCategorySlugRoute
    }
    '/bookmarks/$bookmarkId/': {
      id: '/bookmarks/$bookmarkId/'
      path: '/'
      fullPath: '/bookmarks/$bookmarkId/'
      preLoaderRoute: typeof BookmarksBookmarkIdIndexRouteImport
      parentRoute: typeof BookmarksBookmarkIdRoute
    }
    '/taxonomies/youtube-channels/$channelSlug': {
      id: '/taxonomies/youtube-channels/$channelSlug'
      path: '/$channelSlug'
      fullPath: '/taxonomies/youtube-channels/$channelSlug'
      preLoaderRoute: typeof TaxonomiesYoutubeChannelsChannelSlugRouteImport
      parentRoute: typeof TaxonomiesYoutubeChannelsRoute
    }
    '/taxonomies/websites/$websiteSlug': {
      id: '/taxonomies/websites/$websiteSlug'
      path: '/$websiteSlug'
      fullPath: '/taxonomies/websites/$websiteSlug'
      preLoaderRoute: typeof TaxonomiesWebsitesWebsiteSlugRouteImport
      parentRoute: typeof TaxonomiesWebsitesRoute
    }
    '/taxonomies/media-types/$mediaTypeSlug': {
      id: '/taxonomies/media-types/$mediaTypeSlug'
      path: '/$mediaTypeSlug'
      fullPath: '/taxonomies/media-types/$mediaTypeSlug'
      preLoaderRoute: typeof TaxonomiesMediaTypesMediaTypeSlugRouteImport
      parentRoute: typeof TaxonomiesMediaTypesRoute
    }
    '/settings/custom-properties/new': {
      id: '/settings/custom-properties/new'
      path: '/new'
      fullPath: '/settings/custom-properties/new'
      preLoaderRoute: typeof SettingsCustomPropertiesNewRouteImport
      parentRoute: typeof SettingsCustomPropertiesRoute
    }
    '/settings/custom-properties/$propertySlug': {
      id: '/settings/custom-properties/$propertySlug'
      path: '/$propertySlug'
      fullPath: '/settings/custom-properties/$propertySlug'
      preLoaderRoute: typeof SettingsCustomPropertiesPropertySlugRouteImport
      parentRoute: typeof SettingsCustomPropertiesRoute
    }
    '/settings/autofill/$ruleSlug': {
      id: '/settings/autofill/$ruleSlug'
      path: '/$ruleSlug'
      fullPath: '/settings/autofill/$ruleSlug'
      preLoaderRoute: typeof SettingsAutofillRuleSlugRouteImport
      parentRoute: typeof SettingsAutofillRoute
    }
    '/categories/$categorySlug/edit': {
      id: '/categories/$categorySlug/edit'
      path: '/edit'
      fullPath: '/categories/$categorySlug/edit'
      preLoaderRoute: typeof CategoriesCategorySlugEditRouteImport
      parentRoute: typeof CategoriesCategorySlugRoute
    }
    '/bookmarks/$bookmarkId/edit': {
      id: '/bookmarks/$bookmarkId/edit'
      path: '/edit'
      fullPath: '/bookmarks/$bookmarkId/edit'
      preLoaderRoute: typeof BookmarksBookmarkIdEditRouteImport
      parentRoute: typeof BookmarksBookmarkIdRoute
    }
    '/taxonomies/youtube-channels/$channelSlug/': {
      id: '/taxonomies/youtube-channels/$channelSlug/'
      path: '/'
      fullPath: '/taxonomies/youtube-channels/$channelSlug/'
      preLoaderRoute: typeof TaxonomiesYoutubeChannelsChannelSlugIndexRouteImport
      parentRoute: typeof TaxonomiesYoutubeChannelsChannelSlugRoute
    }
    '/taxonomies/websites/$websiteSlug/': {
      id: '/taxonomies/websites/$websiteSlug/'
      path: '/'
      fullPath: '/taxonomies/websites/$websiteSlug/'
      preLoaderRoute: typeof TaxonomiesWebsitesWebsiteSlugIndexRouteImport
      parentRoute: typeof TaxonomiesWebsitesWebsiteSlugRoute
    }
    '/taxonomies/media-types/$mediaTypeSlug/': {
      id: '/taxonomies/media-types/$mediaTypeSlug/'
      path: '/'
      fullPath: '/taxonomies/media-types/$mediaTypeSlug/'
      preLoaderRoute: typeof TaxonomiesMediaTypesMediaTypeSlugIndexRouteImport
      parentRoute: typeof TaxonomiesMediaTypesMediaTypeSlugRoute
    }
    '/settings/custom-properties/$propertySlug/': {
      id: '/settings/custom-properties/$propertySlug/'
      path: '/'
      fullPath: '/settings/custom-properties/$propertySlug/'
      preLoaderRoute: typeof SettingsCustomPropertiesPropertySlugIndexRouteImport
      parentRoute: typeof SettingsCustomPropertiesPropertySlugRoute
    }
    '/settings/autofill/$ruleSlug/': {
      id: '/settings/autofill/$ruleSlug/'
      path: '/'
      fullPath: '/settings/autofill/$ruleSlug/'
      preLoaderRoute: typeof SettingsAutofillRuleSlugIndexRouteImport
      parentRoute: typeof SettingsAutofillRuleSlugRoute
    }
    '/categories/$categorySlug/edit/': {
      id: '/categories/$categorySlug/edit/'
      path: '/'
      fullPath: '/categories/$categorySlug/edit/'
      preLoaderRoute: typeof CategoriesCategorySlugEditIndexRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/taxonomies/youtube-channels/$channelSlug/edit': {
      id: '/taxonomies/youtube-channels/$channelSlug/edit'
      path: '/edit'
      fullPath: '/taxonomies/youtube-channels/$channelSlug/edit'
      preLoaderRoute: typeof TaxonomiesYoutubeChannelsChannelSlugEditRouteImport
      parentRoute: typeof TaxonomiesYoutubeChannelsChannelSlugRoute
    }
    '/taxonomies/websites/$websiteSlug/edit': {
      id: '/taxonomies/websites/$websiteSlug/edit'
      path: '/edit'
      fullPath: '/taxonomies/websites/$websiteSlug/edit'
      preLoaderRoute: typeof TaxonomiesWebsitesWebsiteSlugEditRouteImport
      parentRoute: typeof TaxonomiesWebsitesWebsiteSlugRoute
    }
    '/taxonomies/media-types/$mediaTypeSlug/edit': {
      id: '/taxonomies/media-types/$mediaTypeSlug/edit'
      path: '/edit'
      fullPath: '/taxonomies/media-types/$mediaTypeSlug/edit'
      preLoaderRoute: typeof TaxonomiesMediaTypesMediaTypeSlugEditRouteImport
      parentRoute: typeof TaxonomiesMediaTypesMediaTypeSlugRoute
    }
    '/settings/custom-properties/$propertySlug/edit': {
      id: '/settings/custom-properties/$propertySlug/edit'
      path: '/edit'
      fullPath: '/settings/custom-properties/$propertySlug/edit'
      preLoaderRoute: typeof SettingsCustomPropertiesPropertySlugEditRouteImport
      parentRoute: typeof SettingsCustomPropertiesPropertySlugRoute
    }
    '/settings/autofill/$ruleSlug/edit': {
      id: '/settings/autofill/$ruleSlug/edit'
      path: '/edit'
      fullPath: '/settings/autofill/$ruleSlug/edit'
      preLoaderRoute: typeof SettingsAutofillRuleSlugEditRouteImport
      parentRoute: typeof SettingsAutofillRuleSlugRoute
    }
    '/categories/$categorySlug/edit/tiered-tags': {
      id: '/categories/$categorySlug/edit/tiered-tags'
      path: '/tiered-tags'
      fullPath: '/categories/$categorySlug/edit/tiered-tags'
      preLoaderRoute: typeof CategoriesCategorySlugEditTieredTagsRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/general': {
      id: '/categories/$categorySlug/edit/general'
      path: '/general'
      fullPath: '/categories/$categorySlug/edit/general'
      preLoaderRoute: typeof CategoriesCategorySlugEditGeneralRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/custom-properties': {
      id: '/categories/$categorySlug/edit/custom-properties'
      path: '/custom-properties'
      fullPath: '/categories/$categorySlug/edit/custom-properties'
      preLoaderRoute: typeof CategoriesCategorySlugEditCustomPropertiesRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
    '/categories/$categorySlug/edit/autofill': {
      id: '/categories/$categorySlug/edit/autofill'
      path: '/autofill'
      fullPath: '/categories/$categorySlug/edit/autofill'
      preLoaderRoute: typeof CategoriesCategorySlugEditAutofillRouteImport
      parentRoute: typeof CategoriesCategorySlugEditRoute
    }
  }
}

interface AutofillRouteChildren {
  AutofillIndexRoute: typeof AutofillIndexRoute
}

const AutofillRouteChildren: AutofillRouteChildren = {
  AutofillIndexRoute: AutofillIndexRoute,
}

const AutofillRouteWithChildren = AutofillRoute._addFileChildren(
  AutofillRouteChildren,
)

interface BookmarksBookmarkIdRouteChildren {
  BookmarksBookmarkIdEditRoute: typeof BookmarksBookmarkIdEditRoute
  BookmarksBookmarkIdIndexRoute: typeof BookmarksBookmarkIdIndexRoute
}

const BookmarksBookmarkIdRouteChildren: BookmarksBookmarkIdRouteChildren = {
  BookmarksBookmarkIdEditRoute: BookmarksBookmarkIdEditRoute,
  BookmarksBookmarkIdIndexRoute: BookmarksBookmarkIdIndexRoute,
}

const BookmarksBookmarkIdRouteWithChildren =
  BookmarksBookmarkIdRoute._addFileChildren(BookmarksBookmarkIdRouteChildren)

interface BookmarksRouteChildren {
  BookmarksBookmarkIdRoute: typeof BookmarksBookmarkIdRouteWithChildren
  BookmarksIndexRoute: typeof BookmarksIndexRoute
}

const BookmarksRouteChildren: BookmarksRouteChildren = {
  BookmarksBookmarkIdRoute: BookmarksBookmarkIdRouteWithChildren,
  BookmarksIndexRoute: BookmarksIndexRoute,
}

const BookmarksRouteWithChildren = BookmarksRoute._addFileChildren(
  BookmarksRouteChildren,
)

interface CustomPropertiesRouteChildren {
  CustomPropertiesIndexRoute: typeof CustomPropertiesIndexRoute
}

const CustomPropertiesRouteChildren: CustomPropertiesRouteChildren = {
  CustomPropertiesIndexRoute: CustomPropertiesIndexRoute,
}

const CustomPropertiesRouteWithChildren =
  CustomPropertiesRoute._addFileChildren(CustomPropertiesRouteChildren)

interface SettingsAutofillRuleSlugRouteChildren {
  SettingsAutofillRuleSlugEditRoute: typeof SettingsAutofillRuleSlugEditRoute
  SettingsAutofillRuleSlugIndexRoute: typeof SettingsAutofillRuleSlugIndexRoute
}

const SettingsAutofillRuleSlugRouteChildren: SettingsAutofillRuleSlugRouteChildren =
  {
    SettingsAutofillRuleSlugEditRoute: SettingsAutofillRuleSlugEditRoute,
    SettingsAutofillRuleSlugIndexRoute: SettingsAutofillRuleSlugIndexRoute,
  }

const SettingsAutofillRuleSlugRouteWithChildren =
  SettingsAutofillRuleSlugRoute._addFileChildren(
    SettingsAutofillRuleSlugRouteChildren,
  )

interface SettingsAutofillRouteChildren {
  SettingsAutofillRuleSlugRoute: typeof SettingsAutofillRuleSlugRouteWithChildren
  SettingsAutofillIndexRoute: typeof SettingsAutofillIndexRoute
}

const SettingsAutofillRouteChildren: SettingsAutofillRouteChildren = {
  SettingsAutofillRuleSlugRoute: SettingsAutofillRuleSlugRouteWithChildren,
  SettingsAutofillIndexRoute: SettingsAutofillIndexRoute,
}

const SettingsAutofillRouteWithChildren =
  SettingsAutofillRoute._addFileChildren(SettingsAutofillRouteChildren)

interface SettingsCustomPropertiesPropertySlugRouteChildren {
  SettingsCustomPropertiesPropertySlugEditRoute: typeof SettingsCustomPropertiesPropertySlugEditRoute
  SettingsCustomPropertiesPropertySlugIndexRoute: typeof SettingsCustomPropertiesPropertySlugIndexRoute
}

const SettingsCustomPropertiesPropertySlugRouteChildren: SettingsCustomPropertiesPropertySlugRouteChildren =
  {
    SettingsCustomPropertiesPropertySlugEditRoute:
      SettingsCustomPropertiesPropertySlugEditRoute,
    SettingsCustomPropertiesPropertySlugIndexRoute:
      SettingsCustomPropertiesPropertySlugIndexRoute,
  }

const SettingsCustomPropertiesPropertySlugRouteWithChildren =
  SettingsCustomPropertiesPropertySlugRoute._addFileChildren(
    SettingsCustomPropertiesPropertySlugRouteChildren,
  )

interface SettingsCustomPropertiesRouteChildren {
  SettingsCustomPropertiesPropertySlugRoute: typeof SettingsCustomPropertiesPropertySlugRouteWithChildren
  SettingsCustomPropertiesNewRoute: typeof SettingsCustomPropertiesNewRoute
  SettingsCustomPropertiesIndexRoute: typeof SettingsCustomPropertiesIndexRoute
}

const SettingsCustomPropertiesRouteChildren: SettingsCustomPropertiesRouteChildren =
  {
    SettingsCustomPropertiesPropertySlugRoute:
      SettingsCustomPropertiesPropertySlugRouteWithChildren,
    SettingsCustomPropertiesNewRoute: SettingsCustomPropertiesNewRoute,
    SettingsCustomPropertiesIndexRoute: SettingsCustomPropertiesIndexRoute,
  }

const SettingsCustomPropertiesRouteWithChildren =
  SettingsCustomPropertiesRoute._addFileChildren(
    SettingsCustomPropertiesRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsAutofillRoute: typeof SettingsAutofillRouteWithChildren
  SettingsAutomationsRoute: typeof SettingsAutomationsRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsCustomPropertiesRoute: typeof SettingsCustomPropertiesRouteWithChildren
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsHomepageRoute: typeof SettingsHomepageRoute
  SettingsMediaTypesRoute: typeof SettingsMediaTypesRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
  SettingsWebsitesRoute: typeof SettingsWebsitesRoute
  SettingsYoutubeChannelsRoute: typeof SettingsYoutubeChannelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAutofillRoute: SettingsAutofillRouteWithChildren,
  SettingsAutomationsRoute: SettingsAutomationsRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsCustomPropertiesRoute: SettingsCustomPropertiesRouteWithChildren,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsHomepageRoute: SettingsHomepageRoute,
  SettingsMediaTypesRoute: SettingsMediaTypesRoute,
  SettingsTagsRoute: SettingsTagsRoute,
  SettingsWebsitesRoute: SettingsWebsitesRoute,
  SettingsYoutubeChannelsRoute: SettingsYoutubeChannelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface CategoriesCategorySlugEditRouteChildren {
  CategoriesCategorySlugEditAutofillRoute: typeof CategoriesCategorySlugEditAutofillRoute
  CategoriesCategorySlugEditCustomPropertiesRoute: typeof CategoriesCategorySlugEditCustomPropertiesRoute
  CategoriesCategorySlugEditGeneralRoute: typeof CategoriesCategorySlugEditGeneralRoute
  CategoriesCategorySlugEditTieredTagsRoute: typeof CategoriesCategorySlugEditTieredTagsRoute
  CategoriesCategorySlugEditIndexRoute: typeof CategoriesCategorySlugEditIndexRoute
}

const CategoriesCategorySlugEditRouteChildren: CategoriesCategorySlugEditRouteChildren =
  {
    CategoriesCategorySlugEditAutofillRoute:
      CategoriesCategorySlugEditAutofillRoute,
    CategoriesCategorySlugEditCustomPropertiesRoute:
      CategoriesCategorySlugEditCustomPropertiesRoute,
    CategoriesCategorySlugEditGeneralRoute:
      CategoriesCategorySlugEditGeneralRoute,
    CategoriesCategorySlugEditTieredTagsRoute:
      CategoriesCategorySlugEditTieredTagsRoute,
    CategoriesCategorySlugEditIndexRoute: CategoriesCategorySlugEditIndexRoute,
  }

const CategoriesCategorySlugEditRouteWithChildren =
  CategoriesCategorySlugEditRoute._addFileChildren(
    CategoriesCategorySlugEditRouteChildren,
  )

interface CategoriesCategorySlugRouteChildren {
  CategoriesCategorySlugEditRoute: typeof CategoriesCategorySlugEditRouteWithChildren
  CategoriesCategorySlugIndexRoute: typeof CategoriesCategorySlugIndexRoute
}

const CategoriesCategorySlugRouteChildren: CategoriesCategorySlugRouteChildren =
  {
    CategoriesCategorySlugEditRoute:
      CategoriesCategorySlugEditRouteWithChildren,
    CategoriesCategorySlugIndexRoute: CategoriesCategorySlugIndexRoute,
  }

const CategoriesCategorySlugRouteWithChildren =
  CategoriesCategorySlugRoute._addFileChildren(
    CategoriesCategorySlugRouteChildren,
  )

interface TaxonomiesMediaTypesMediaTypeSlugRouteChildren {
  TaxonomiesMediaTypesMediaTypeSlugEditRoute: typeof TaxonomiesMediaTypesMediaTypeSlugEditRoute
  TaxonomiesMediaTypesMediaTypeSlugIndexRoute: typeof TaxonomiesMediaTypesMediaTypeSlugIndexRoute
}

const TaxonomiesMediaTypesMediaTypeSlugRouteChildren: TaxonomiesMediaTypesMediaTypeSlugRouteChildren =
  {
    TaxonomiesMediaTypesMediaTypeSlugEditRoute:
      TaxonomiesMediaTypesMediaTypeSlugEditRoute,
    TaxonomiesMediaTypesMediaTypeSlugIndexRoute:
      TaxonomiesMediaTypesMediaTypeSlugIndexRoute,
  }

const TaxonomiesMediaTypesMediaTypeSlugRouteWithChildren =
  TaxonomiesMediaTypesMediaTypeSlugRoute._addFileChildren(
    TaxonomiesMediaTypesMediaTypeSlugRouteChildren,
  )

interface TaxonomiesMediaTypesRouteChildren {
  TaxonomiesMediaTypesMediaTypeSlugRoute: typeof TaxonomiesMediaTypesMediaTypeSlugRouteWithChildren
  TaxonomiesMediaTypesIndexRoute: typeof TaxonomiesMediaTypesIndexRoute
}

const TaxonomiesMediaTypesRouteChildren: TaxonomiesMediaTypesRouteChildren = {
  TaxonomiesMediaTypesMediaTypeSlugRoute:
    TaxonomiesMediaTypesMediaTypeSlugRouteWithChildren,
  TaxonomiesMediaTypesIndexRoute: TaxonomiesMediaTypesIndexRoute,
}

const TaxonomiesMediaTypesRouteWithChildren =
  TaxonomiesMediaTypesRoute._addFileChildren(TaxonomiesMediaTypesRouteChildren)

interface TaxonomiesWebsitesWebsiteSlugRouteChildren {
  TaxonomiesWebsitesWebsiteSlugEditRoute: typeof TaxonomiesWebsitesWebsiteSlugEditRoute
  TaxonomiesWebsitesWebsiteSlugIndexRoute: typeof TaxonomiesWebsitesWebsiteSlugIndexRoute
}

const TaxonomiesWebsitesWebsiteSlugRouteChildren: TaxonomiesWebsitesWebsiteSlugRouteChildren =
  {
    TaxonomiesWebsitesWebsiteSlugEditRoute:
      TaxonomiesWebsitesWebsiteSlugEditRoute,
    TaxonomiesWebsitesWebsiteSlugIndexRoute:
      TaxonomiesWebsitesWebsiteSlugIndexRoute,
  }

const TaxonomiesWebsitesWebsiteSlugRouteWithChildren =
  TaxonomiesWebsitesWebsiteSlugRoute._addFileChildren(
    TaxonomiesWebsitesWebsiteSlugRouteChildren,
  )

interface TaxonomiesWebsitesRouteChildren {
  TaxonomiesWebsitesWebsiteSlugRoute: typeof TaxonomiesWebsitesWebsiteSlugRouteWithChildren
  TaxonomiesWebsitesIndexRoute: typeof TaxonomiesWebsitesIndexRoute
}

const TaxonomiesWebsitesRouteChildren: TaxonomiesWebsitesRouteChildren = {
  TaxonomiesWebsitesWebsiteSlugRoute:
    TaxonomiesWebsitesWebsiteSlugRouteWithChildren,
  TaxonomiesWebsitesIndexRoute: TaxonomiesWebsitesIndexRoute,
}

const TaxonomiesWebsitesRouteWithChildren =
  TaxonomiesWebsitesRoute._addFileChildren(TaxonomiesWebsitesRouteChildren)

interface TaxonomiesYoutubeChannelsChannelSlugRouteChildren {
  TaxonomiesYoutubeChannelsChannelSlugEditRoute: typeof TaxonomiesYoutubeChannelsChannelSlugEditRoute
  TaxonomiesYoutubeChannelsChannelSlugIndexRoute: typeof TaxonomiesYoutubeChannelsChannelSlugIndexRoute
}

const TaxonomiesYoutubeChannelsChannelSlugRouteChildren: TaxonomiesYoutubeChannelsChannelSlugRouteChildren =
  {
    TaxonomiesYoutubeChannelsChannelSlugEditRoute:
      TaxonomiesYoutubeChannelsChannelSlugEditRoute,
    TaxonomiesYoutubeChannelsChannelSlugIndexRoute:
      TaxonomiesYoutubeChannelsChannelSlugIndexRoute,
  }

const TaxonomiesYoutubeChannelsChannelSlugRouteWithChildren =
  TaxonomiesYoutubeChannelsChannelSlugRoute._addFileChildren(
    TaxonomiesYoutubeChannelsChannelSlugRouteChildren,
  )

interface TaxonomiesYoutubeChannelsRouteChildren {
  TaxonomiesYoutubeChannelsChannelSlugRoute: typeof TaxonomiesYoutubeChannelsChannelSlugRouteWithChildren
  TaxonomiesYoutubeChannelsIndexRoute: typeof TaxonomiesYoutubeChannelsIndexRoute
}

const TaxonomiesYoutubeChannelsRouteChildren: TaxonomiesYoutubeChannelsRouteChildren =
  {
    TaxonomiesYoutubeChannelsChannelSlugRoute:
      TaxonomiesYoutubeChannelsChannelSlugRouteWithChildren,
    TaxonomiesYoutubeChannelsIndexRoute: TaxonomiesYoutubeChannelsIndexRoute,
  }

const TaxonomiesYoutubeChannelsRouteWithChildren =
  TaxonomiesYoutubeChannelsRoute._addFileChildren(
    TaxonomiesYoutubeChannelsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutofillRoute: AutofillRouteWithChildren,
  BookmarksRoute: BookmarksRouteWithChildren,
  CustomPropertiesRoute: CustomPropertiesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRouteWithChildren,
  TaxonomiesMediaTypesRoute: TaxonomiesMediaTypesRouteWithChildren,
  TaxonomiesTagsRoute: TaxonomiesTagsRoute,
  TaxonomiesWebsitesRoute: TaxonomiesWebsitesRouteWithChildren,
  TaxonomiesYoutubeChannelsRoute: TaxonomiesYoutubeChannelsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
