import { eq, ne, or, sql } from "drizzle-orm";
import type { Website, WebsiteExtensionFillRule, WebsiteNode } from "@eesimple/types";
import { db } from "@/db";
import { categories, websiteFavicons, websites } from "@/db/schema";
import { AppError } from "@/utils/errors";
import { slugify } from "@/utils/slug";

/**
 * Build a favicon serving URL (with a `?v=` cache-buster) from a website id and its favicon's
 * `createdAt`, or `null` when there's no favicon. Kept in sync with `websiteFaviconUrl` in the
 * favicon service — both encode the version the same way so a replaced favicon busts the cache.
 */
export function faviconUrlFrom(websiteId: string, createdAt: Date | string | null): string | null {
  if (!createdAt) return null;
  const time = (createdAt instanceof Date ? createdAt : new Date(createdAt)).getTime();
  return `/api/websites/${websiteId}/image?v=${time}`;
}

/** Transaction handle type, matching the callback arg of `db.transaction`. */
export type Tx = Parameters<Parameters<typeof db.transaction>[0]>[0];

/** Thrown when a website rename/move would collide with an existing domain. */
export class DuplicateDomainError extends AppError {
  constructor(domain: string) {
    super(`A website already exists for "${domain}"`, "duplicateDomain", 409, {
      domain,
    });
  }
}

/** Thrown when an update or delete targets a built-in website in a disallowed way. */
export class BuiltInWebsiteError extends AppError {
  constructor(message: string) {
    super(message, "builtInImmutable", 403);
  }
}

/** Thrown when a manual create is given a domain that normalizes to an empty host. */
export class InvalidDomainError extends AppError {
  constructor() {
    super("A non-empty domain is required", "validation", 400);
  }
}

/**
 * SQL predicate matching a website by its canonical `domain` OR any of its verified
 * `shortenedLinks[].domain` (so e.g. a `youtu.be` URL resolves to the `youtube.com` site). Uses
 * jsonb containment (`@>`) for partial-object matching within the array.
 */
export function matchesAnyDomain(domain: string) {
  return or(
    eq(websites.domain, domain),
    sql`${websites.shortenedLinks} @> ${JSON.stringify([{
      domain,
    }])}::jsonb`,
  );
}

/**
 * Derive a URL-safe slug base from a domain by stripping the TLD (last dot-segment) and
 * slugifying. `"github.com"` → `"github"`, `"news.ycombinator.com"` → `"news-ycombinator"`.
 */
export function slugFromDomain(domain: string): string {
  const withoutTld = domain.replace(/\.[^.]+$/, "");
  return slugify(withoutTld) || slugify(domain) || "website";
}

/**
 * Pick a website slug for `base` that does not collide with `taken`. Appends `-2`, `-3`, …
 * until unique.
 */
export function uniqueWebsiteSlug(base: string, taken: Set<string>): string {
  if (!taken.has(base)) return base;
  for (let n = 2; ; n += 1) {
    const candidate = `${base}-${n}`;
    if (!taken.has(candidate)) return candidate;
  }
}

/** Fetch the set of all existing website slugs, optionally excluding one row. */
export async function takenWebsiteSlugs(excludeId?: string): Promise<Set<string>> {
  const rows = await db
    .select({
      slug: websites.slug,
    })
    .from(websites)
    .where(excludeId ? ne(websites.id, excludeId) : undefined);
  return new Set(rows.map(r => r.slug).filter((s): s is string => s !== null));
}

/**
 * Normalize a URL to its host for the Websites taxonomy: lower-cased, leading `www.` stripped.
 * Mirrors the client's `hostOf()` so both sides agree on a bookmark's website. Pure — returns
 * `null` for any value that isn't a parseable URL with a host.
 */
export function normalizeDomain(url: string): string | null {
  try {
    const host = new URL(url).hostname.replace(/^www\./i, "").toLowerCase();
    return host.length > 0 ? host : null;
  }
  catch {
    return null;
  }
}

/**
 * Derive the brand label from a domain: the registrable name before the public suffix, e.g.
 * `github` from `github.com` or `sub.github.com`. A best-effort heuristic used only for cleaning
 * up fetched titles.
 */
function brandFromDomain(domain: string): string {
  const labels = domain.split(".").filter(Boolean);
  if (labels.length >= 2) return labels[labels.length - 2];
  return labels[0] ?? domain;
}

/** Escape a string for safe inclusion in a `RegExp`. */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Strip a trailing site-name/brand suffix from an autogenerated title so site names aren't
 * appended to titles (e.g. `"Pricing · GitHub"` → `"Pricing"`). Matches a trailing separator
 * followed by the site name or the domain's brand label, only when a non-empty prefix remains.
 * Pure — kept separate from DB access for unit testing.
 */
export function stripSiteNameSuffix(
  title: string,
  {
    siteName, domain,
  }: { siteName?: string | null;
    domain?: string | null; },
): string {
  const candidates: string[] = [];
  if (siteName && siteName.trim().length > 0) candidates.push(siteName.trim());
  if (domain) candidates.push(brandFromDomain(domain));

  for (const token of candidates) {
    if (token.length === 0) continue;
    // Trailing separator (dash/pipe/colon/dot variants) + the token at the very end.
    const re = new RegExp(`\\s*[-|–—·•:／]\\s*${escapeRegExp(token)}\\s*$`, "i");
    if (!re.test(title)) continue;
    const stripped = title.replace(re, "").trim();
    if (stripped.length > 0) return stripped;
  }
  return title;
}

/** Shared select shape for website lookups (includes favicon + category join fields). */
export const websiteSelect = {
  id: websites.id,
  domain: websites.domain,
  siteName: websites.siteName,
  slug: websites.slug,
  description: websites.description,
  builtIn: websites.builtIn,
  isFavorite: websites.isFavorite,
  shortenedLinks: websites.shortenedLinks,
  paramRules: websites.paramRules,
  socialLinks: websites.socialLinks,
  labeledWebsites: websites.labeledWebsites,
  alternateNames: websites.alternateNames,
  extensionFillRules: websites.extensionFillRules,
  extensionFillRuleGroups: websites.extensionFillRuleGroups,
  scanObservations: websites.scanObservations,
  createdAt: websites.createdAt,
  categoryId: websites.categoryId,
  mediaTypeId: websites.mediaTypeId,
  faviconAutoGrabError: websites.faviconAutoGrabError,
  redirectResolutionFailure: websites.redirectResolutionFailure,
  scanUrlForIsbn: websites.scanUrlForIsbn,
  faviconCreatedAt: websiteFavicons.createdAt,
  categoryName: categories.name,
  categorySlug: categories.slug,
  categoryIcon: categories.icon,
};

/**
 * Find the parent domain of a domain in the given domain set: the longest-suffix candidate that
 * exists as a website (e.g. `blog.example.com` → `example.com`). Pure — no DB access.
 */
function findParentDomain(domain: string, domainSet: Set<string>): string | null {
  const parts = domain.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    const candidate = parts.slice(i).join(".");
    if (domainSet.has(candidate)) return candidate;
  }
  return null;
}

/**
 * Build a nested tree from a flat website list, grouping subdomains under their parent domains.
 * Pure — kept separate from DB access so it can be unit-tested.
 */
export function buildWebsiteTree(all: Website[]): WebsiteNode[] {
  const domainSet = new Set(all.map(w => w.domain));
  const byDomain = new Map<string, WebsiteNode>(
    all.map(w => [w.domain, {
      ...w,
      children: [],
    }]),
  );
  const roots: WebsiteNode[] = [];
  for (const node of byDomain.values()) {
    const parentDomain = findParentDomain(node.domain, domainSet);
    const parent = parentDomain ? byDomain.get(parentDomain) : undefined;
    if (parent) parent.children.push(node);
    else roots.push(node);
  }
  return roots;
}

/** A stored extension-fill rule as it may exist on disk, including the retired `pathSuffix` field. */
export type LegacyExtensionFillRule = WebsiteExtensionFillRule & { pathSuffix?: string };

/**
 * Convert one website's rules from the retired suffix-only `pathSuffix` gate to the mode-based
 * `pathMatch` (as a `suffix` match, preserving today's behavior). Returns the migrated array only
 * when something changed, else `null` — the caller skips a no-op write, keeping the boot step
 * idempotent. An already-migrated rule (`pathMatch` present, no `pathSuffix`) is left untouched.
 */
export function migrateExtensionFillRules(
  rules: LegacyExtensionFillRule[],
): WebsiteExtensionFillRule[] | null {
  let changed = false;
  const migrated = rules.map((rule): WebsiteExtensionFillRule => {
    const {
      pathSuffix, ...rest
    } = rule;
    if (pathSuffix === undefined) return rule;
    changed = true;
    // A blank legacy suffix was an always-apply gate — drop it entirely.
    const trimmed = pathSuffix.trim();
    if (!trimmed || rest.pathMatch) return rest;
    return {
      ...rest,
      pathMatch: {
        mode: "suffix",
        value: trimmed,
      },
    };
  });
  return changed ? migrated : null;
}
