import { asc, eq, isNull, ne, sql } from "drizzle-orm";
import type { CreateWebsiteInput, UpdateWebsiteInput, Website } from "@eesimple/types";
import { db } from "@/db";
import { bookmarks, websites, type WebsiteRow } from "@/db/schema";
import { slugify } from "@/utils/slug";

/** Transaction handle type, matching the callback arg of `db.transaction`. */
type Tx = Parameters<Parameters<typeof db.transaction>[0]>[0];

/** Thrown when a website rename/move would collide with an existing domain. */
export class DuplicateDomainError extends Error {
  constructor(domain: string) {
    super(`A website already exists for "${domain}"`);
    this.name = "DuplicateDomainError";
  }
}

/** Thrown when an update or delete targets a built-in website in a disallowed way. */
export class BuiltInWebsiteError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BuiltInWebsiteError";
  }
}

/** Seeded built-in websites, kept in sync at boot. Built-ins can't be renamed or deleted. */
const BUILT_IN_WEBSITES: { domain: string;
  siteName: string; }[] = [
  {
    domain: "youtube.com",
    siteName: "YouTube",
  },
];

/**
 * Derive a URL-safe slug base from a domain by stripping the TLD (last dot-segment) and
 * slugifying. `"github.com"` → `"github"`, `"news.ycombinator.com"` → `"news-ycombinator"`.
 */
function slugFromDomain(domain: string): string {
  const withoutTld = domain.replace(/\.[^.]+$/, "");
  return slugify(withoutTld) || slugify(domain) || "website";
}

/**
 * Pick a website slug for `base` that does not collide with `taken`. Appends `-2`, `-3`, …
 * until unique.
 */
function uniqueWebsiteSlug(base: string, taken: Set<string>): string {
  if (!taken.has(base)) return base;
  for (let n = 2; ; n += 1) {
    const candidate = `${base}-${n}`;
    if (!taken.has(candidate)) return candidate;
  }
}

/** Fetch the set of all existing website slugs, optionally excluding one row. */
async function takenWebsiteSlugs(excludeId?: string): Promise<Set<string>> {
  const rows = await db
    .select({
      slug: websites.slug,
    })
    .from(websites)
    .where(excludeId ? ne(websites.id, excludeId) : undefined);
  return new Set(rows.map(r => r.slug).filter((s): s is string => s !== null));
}

/** Map a DB row to the shared `Website` wire type. */
function toWebsite(row: WebsiteRow & { bookmarkCount?: number }): Website {
  return {
    id: row.id,
    domain: row.domain,
    siteName: row.siteName,
    slug: row.slug ?? slugFromDomain(row.domain),
    builtIn: row.builtIn,
    createdAt:
      row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt),
    bookmarkCount: row.bookmarkCount,
  };
}

/**
 * Normalize a URL to its host for the Websites taxonomy: lower-cased, leading `www.` stripped.
 * Mirrors the client's `hostOf()` so both sides agree on a bookmark's website. Pure — returns
 * `null` for any value that isn't a parseable URL with a host.
 */
export function normalizeDomain(url: string): string | null {
  try {
    const host = new URL(url).hostname.replace(/^www\./i, "").toLowerCase();
    return host.length > 0 ? host : null;
  }
  catch {
    return null;
  }
}

/**
 * Derive the brand label from a domain: the registrable name before the public suffix, e.g.
 * `github` from `github.com` or `sub.github.com`. A best-effort heuristic used only for cleaning
 * up fetched titles.
 */
function brandFromDomain(domain: string): string {
  const labels = domain.split(".").filter(Boolean);
  if (labels.length >= 2) return labels[labels.length - 2];
  return labels[0] ?? domain;
}

/** Escape a string for safe inclusion in a `RegExp`. */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Strip a trailing site-name/brand suffix from an autogenerated title so site names aren't
 * appended to titles (e.g. `"Pricing · GitHub"` → `"Pricing"`). Matches a trailing separator
 * followed by the site name or the domain's brand label, only when a non-empty prefix remains.
 * Pure — kept separate from DB access for unit testing.
 */
export function stripSiteNameSuffix(
  title: string,
  {
    siteName, domain,
  }: { siteName?: string | null;
    domain?: string | null; },
): string {
  const candidates: string[] = [];
  if (siteName && siteName.trim().length > 0) candidates.push(siteName.trim());
  if (domain) candidates.push(brandFromDomain(domain));

  for (const token of candidates) {
    if (token.length === 0) continue;
    // Trailing separator (dash/pipe/colon/dot variants) + the token at the very end.
    const re = new RegExp(`\\s*[-|–—·•:]\\s*${escapeRegExp(token)}\\s*$`, "i");
    if (!re.test(title)) continue;
    const stripped = title.replace(re, "").trim();
    if (stripped.length > 0) return stripped;
  }
  return title;
}

/** List all websites, ordered by site name. */
export async function listWebsites(): Promise<Website[]> {
  const rows = await db
    .select({
      id: websites.id,
      domain: websites.domain,
      siteName: websites.siteName,
      slug: websites.slug,
      builtIn: websites.builtIn,
      createdAt: websites.createdAt,
      bookmarkCount: sql<number>`(select count(*)::int from ${bookmarks} where ${bookmarks.websiteId} = ${websites.id})`.mapWith(Number),
    })
    .from(websites)
    .orderBy(asc(websites.siteName));
  return rows.map(toWebsite);
}

/** Fetch a single website by id, or `null` when absent. */
export async function getWebsite(id: string): Promise<Website | null> {
  const [row] = await db.select().from(websites).where(eq(websites.id, id));
  return row ? toWebsite(row) : null;
}

/** Fetch a website by its normalized domain, or `null` when absent. */
export async function getWebsiteByDomain(domain: string): Promise<Website | null> {
  const [row] = await db.select().from(websites).where(eq(websites.domain, domain));
  return row ? toWebsite(row) : null;
}

/**
 * Resolve the website for a URL inside a transaction, creating it when none exists yet.
 * `siteName` sets the friendly name for the new site; defaults to the domain when omitted.
 * Returns the website id, or `null` when the URL has no host.
 */
export async function ensureWebsiteForUrl(tx: Tx, url: string, siteName?: string): Promise<string | null> {
  const domain = normalizeDomain(url);
  if (!domain) return null;

  const [existing] = await tx
    .select({
      id: websites.id,
    })
    .from(websites)
    .where(eq(websites.domain, domain));
  if (existing) return existing.id;

  // Generate a slug before inserting (read outside tx is safe — backfill covers edge cases).
  const taken = await takenWebsiteSlugs();
  const slug = uniqueWebsiteSlug(slugFromDomain(domain), taken);

  const inserted = await tx
    .insert(websites)
    .values({
      domain,
      siteName: siteName?.trim() || domain,
      slug,
    })
    .onConflictDoNothing({
      target: websites.domain,
    })
    .returning({
      id: websites.id,
    });
  if (inserted.length > 0) return inserted[0].id;

  // Lost a concurrent insert race — re-read the row the other writer created.
  const [row] = await tx
    .select({
      id: websites.id,
    })
    .from(websites)
    .where(eq(websites.domain, domain));
  return row?.id ?? null;
}

/**
 * Look up the website for a URL without creating one — powers the add-bookmark banner. Returns
 * the normalized domain (or `null`) and the existing website (or `null`).
 */
export async function lookupWebsiteByUrl(
  url: string,
): Promise<{ domain: string | null;
  website: Website | null; }> {
  const domain = normalizeDomain(url);
  if (!domain) return {
    domain: null,
    website: null,
  };
  return {
    domain,
    website: await getWebsiteByDomain(domain),
  };
}

/** Thrown when a manual create is given a domain that normalizes to an empty host. */
export class InvalidDomainError extends Error {
  constructor() {
    super("A non-empty domain is required");
    this.name = "InvalidDomainError";
  }
}

/**
 * Manually add a website to the taxonomy. The `domain` is treated as a raw host (not a full URL),
 * normalized the same way `updateWebsite` does. Throws `InvalidDomainError` for an empty host and
 * `DuplicateDomainError` when the domain already exists.
 */
export async function createWebsite(input: CreateWebsiteInput): Promise<Website> {
  const domain = input.domain.trim().replace(/^www\./i, "").toLowerCase();
  if (domain.length === 0) throw new InvalidDomainError();

  const existing = await getWebsiteByDomain(domain);
  if (existing) throw new DuplicateDomainError(domain);

  const siteName = input.siteName?.trim() ? input.siteName.trim() : domain;
  const taken = await takenWebsiteSlugs();
  const slug = uniqueWebsiteSlug(slugFromDomain(domain), taken);

  const [row] = await db.insert(websites).values({
    domain,
    siteName,
    slug,
  }).returning();
  return toWebsite(row);
}

/** Rename a website's site name and/or change its domain. Returns the updated row, or `null`. */
export async function updateWebsite(
  id: string,
  input: UpdateWebsiteInput,
): Promise<Website | null> {
  const [existing] = await db.select().from(websites).where(eq(websites.id, id));
  if (!existing) return null;
  if (existing.builtIn) {
    const renames = input.siteName !== undefined && input.siteName.trim() !== existing.siteName;
    const moves = input.domain !== undefined
      && input.domain.replace(/^www\./i, "").toLowerCase() !== existing.domain;
    if (renames || moves) {
      throw new BuiltInWebsiteError("A built-in website cannot be renamed or moved");
    }
  }

  const patch: Partial<Pick<WebsiteRow, "domain" | "siteName" | "slug">> = {};
  if (input.siteName !== undefined) patch.siteName = input.siteName;
  if (input.domain !== undefined) {
    const domain = input.domain.replace(/^www\./i, "").toLowerCase();
    const clash = await getWebsiteByDomain(domain);
    if (clash && clash.id !== id) throw new DuplicateDomainError(domain);
    patch.domain = domain;
    // Regenerate the slug when the domain changes since it derives from the domain.
    const taken = await takenWebsiteSlugs(id);
    patch.slug = uniqueWebsiteSlug(slugFromDomain(domain), taken);
  }
  if (Object.keys(patch).length === 0) return getWebsite(id);

  const [row] = await db.update(websites).set(patch).where(eq(websites.id, id)).returning();
  return row ? toWebsite(row) : null;
}

/** Delete a website. Built-ins can't be deleted. Bookmarks pointing at it are set to NULL via FK. */
export async function deleteWebsite(id: string): Promise<boolean> {
  const [existing] = await db.select({
    builtIn: websites.builtIn,
  }).from(websites).where(eq(websites.id, id));
  if (!existing) return false;
  if (existing.builtIn) throw new BuiltInWebsiteError("A built-in website cannot be deleted");
  const rows = await db.delete(websites).where(eq(websites.id, id)).returning({
    id: websites.id,
  });
  return rows.length > 0;
}

/**
 * Ensure the seeded built-in websites exist and are marked built-in. Idempotent and safe to call at
 * boot: inserts any missing built-in by domain, and upgrades a pre-existing auto-created row (e.g. a
 * youtube.com site created before seeding) to `builtIn` with the canonical site name. The slug is
 * only set on insert, preserving any slug an existing row already has.
 */
export async function ensureBuiltInWebsites(): Promise<void> {
  for (const {
    domain, siteName,
  } of BUILT_IN_WEBSITES) {
    const taken = await takenWebsiteSlugs();
    const slug = uniqueWebsiteSlug(slugFromDomain(domain), taken);
    await db
      .insert(websites)
      .values({
        domain,
        siteName,
        slug,
        builtIn: true,
      })
      .onConflictDoUpdate({
        target: websites.domain,
        set: {
          builtIn: true,
          siteName,
        },
      });
  }
}

/** Fill in slugs for any websites missing one (e.g. rows that predate the `slug` column). */
export async function backfillWebsiteSlugs(): Promise<void> {
  const missing = await db
    .select({
      id: websites.id,
      domain: websites.domain,
    })
    .from(websites)
    .where(isNull(websites.slug));
  if (missing.length === 0) return;

  const taken = await takenWebsiteSlugs();
  for (const site of missing) {
    const slug = uniqueWebsiteSlug(slugFromDomain(site.domain), taken);
    taken.add(slug);
    await db.update(websites).set({
      slug,
    }).where(eq(websites.id, site.id));
  }
}
