import type { EntityLayout, LayoutSection, LayoutTab } from "@eesimple/types";

/**
 * Pure, immutable reducers over an {@link EntityLayout} for the `LayoutBoard` drag-and-drop editor
 * (#1160). Every function returns a fresh layout and never mutates its argument, so the board stays a
 * thin controlled component and the branch-heavy move/guard-rail logic is unit-testable on its own —
 * the sibling of `cardFieldPlacementMove.ts` for the fixed-zone card board.
 *
 * Field keys are globally unique across the entity's field registry, so a field lives in at most one
 * section; a field absent from every section resolves back to its default home (surfaced as the
 * editor's "Unplaced" tray). Container `key`s are stable machine slugs generated by
 * {@link makeContainerKey}; `label`/`title` are the user-editable display strings.
 */

/** A field's destination: a specific section, or `null` for the unplaced tray. */
export interface FieldTarget {
  tabKey: string;
  sectionKey: string;
}

/** Slugify a display string into a machine-key base (lowercase, hyphen-separated ASCII). */
function slugify(text: string): string {
  return text.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/**
 * A deterministic unique container key: the slug of `base` (falling back to `fallback` when the slug
 * is empty), suffixed with `-2`, `-3`, … until it is absent from `existingKeys`. Deterministic (no
 * `Date.now()`/`Math.random()`) so callers and tests get stable keys.
 */
export function makeContainerKey(base: string, existingKeys: Set<string>, fallback = "item"): string {
  const root = slugify(base) || fallback;
  if (!existingKeys.has(root)) return root;
  let suffix = 2;
  while (existingKeys.has(`${root}-${suffix}`)) suffix += 1;
  return `${root}-${suffix}`;
}

/** All tab keys in `layout`. */
function tabKeys(layout: EntityLayout): Set<string> {
  return new Set(layout.tabs.map(tab => tab.key));
}

/** All section keys within `tab`. */
function sectionKeys(tab: LayoutTab): Set<string> {
  return new Set(tab.sections.map(section => section.key));
}

/** Map every tab, replacing the one keyed `tabKey` with `fn(tab)`; others pass through unchanged. */
function mapTab(layout: EntityLayout, tabKey: string, fn: (tab: LayoutTab) => LayoutTab): EntityLayout {
  return {
    tabs: layout.tabs.map(tab => (tab.key === tabKey ? fn(tab) : tab)),
  };
}

/** Map every section of `tab`, replacing the one keyed `sectionKey` with `fn(section)`. */
function mapSection(
  tab: LayoutTab,
  sectionKey: string,
  fn: (section: LayoutSection) => LayoutSection,
): LayoutTab {
  return {
    ...tab,
    sections: tab.sections.map(section => (section.key === sectionKey ? fn(section) : section)),
  };
}

/**
 * Move `fieldKey` into `target` at `index` (appended when `index` is omitted), or remove it from the
 * layout entirely when `target` is `null` (→ it falls to the tray). The field is first stripped from
 * wherever it currently sits, so this both relocates a placed field and places a tray field. A `null`
 * target on an already-unplaced field, or a target section that doesn't exist, is a no-op beyond the
 * strip. Direct analog of `CardFieldZoneBoard`'s `moveKey`.
 */
export function moveField(
  layout: EntityLayout,
  fieldKey: string,
  target: FieldTarget | null,
  index?: number,
): EntityLayout {
  const stripped: EntityLayout = {
    tabs: layout.tabs.map(tab => ({
      ...tab,
      sections: tab.sections.map(section => ({
        ...section,
        fields: section.fields.filter(field => field !== fieldKey),
      })),
    })),
  };
  if (!target) return stripped;

  return mapTab(stripped, target.tabKey, tab => mapSection(tab, target.sectionKey, (section) => {
    const at = index === undefined
      ? section.fields.length
      : Math.min(Math.max(index, 0), section.fields.length);
    const fields = [...section.fields];
    fields.splice(at, 0, fieldKey);
    return {
      ...section,
      fields,
    };
  }));
}

/** Append a new tab (untitled, one empty untitled section) with a generated unique key. */
export function addTab(layout: EntityLayout, label: string): EntityLayout {
  const key = makeContainerKey(label, tabKeys(layout), "tab");
  const tab: LayoutTab = {
    key,
    label,
    sections: [{
      key: "section",
      fields: [],
    }],
  };
  return {
    tabs: [...layout.tabs, tab],
  };
}

/** Append a new section to `tabKey` with a generated unique key. `title` empty → untitled. */
export function addSection(layout: EntityLayout, tabKey: string, title = ""): EntityLayout {
  return mapTab(layout, tabKey, (tab) => {
    const key = makeContainerKey(title, sectionKeys(tab), "section");
    const section: LayoutSection = title
      ? {
        key,
        title,
        fields: [],
      }
      : {
        key,
        fields: [],
      };
    return {
      ...tab,
      sections: [...tab.sections, section],
    };
  });
}

/** Rename a tab's user-facing label (its machine `key` is unchanged). */
export function renameTab(layout: EntityLayout, tabKey: string, label: string): EntityLayout {
  return mapTab(layout, tabKey, tab => ({
    ...tab,
    label,
  }));
}

/** Set (or clear, when `icon` is `undefined`) a tab's serialized icon name. */
export function setTabIcon(layout: EntityLayout, tabKey: string, icon: string | undefined): EntityLayout {
  return mapTab(layout, tabKey, (tab) => {
    const next: LayoutTab = {
      ...tab,
    };
    if (icon) next.icon = icon;
    else delete next.icon;
    return next;
  });
}

/** Rename a section's title. Empty string → untitled (the `title` key is dropped). */
export function renameSection(
  layout: EntityLayout,
  tabKey: string,
  sectionKey: string,
  title: string,
): EntityLayout {
  return mapTab(layout, tabKey, tab => mapSection(tab, sectionKey, (section) => {
    const next: LayoutSection = {
      ...section,
    };
    if (title) next.title = title;
    else delete next.title;
    return next;
  }));
}

/**
 * Set a section's column count (1–4; fields render at `1/columns` width). A value of `1` (or
 * `undefined`) drops the `columns` key so a full-width section stays a clean `{ key, fields }`
 * literal — the default. Mirrors {@link setTabIcon}'s set-or-clear shape.
 */
export function setSectionColumns(
  layout: EntityLayout,
  tabKey: string,
  sectionKey: string,
  columns: number | undefined,
): EntityLayout {
  return mapTab(layout, tabKey, tab => mapSection(tab, sectionKey, (section) => {
    const next: LayoutSection = {
      ...section,
    };
    if (columns && columns > 1) next.columns = columns;
    else delete next.columns;
    return next;
  }));
}

/**
 * Delete a tab; any fields it held become unplaced (→ tray). Guard: a no-op when it is the only tab,
 * so at least one tab always exists.
 */
export function deleteTab(layout: EntityLayout, tabKey: string): EntityLayout {
  if (layout.tabs.length <= 1) return layout;
  return {
    tabs: layout.tabs.filter(tab => tab.key !== tabKey),
  };
}

/**
 * Delete a section; any fields it held become unplaced (→ tray). Guard: a no-op when it is the tab's
 * only section AND that section still holds ≥1 field ("can't delete a tab's last section while fields
 * remain") — an empty last section may be deleted, leaving a section-less tab the editor still shows.
 */
export function deleteSection(layout: EntityLayout, tabKey: string, sectionKey: string): EntityLayout {
  const tab = layout.tabs.find(candidate => candidate.key === tabKey);
  if (!tab) return layout;
  const section = tab.sections.find(candidate => candidate.key === sectionKey);
  if (!section) return layout;
  if (tab.sections.length <= 1 && section.fields.length > 0) return layout;
  return mapTab(layout, tabKey, current => ({
    ...current,
    sections: current.sections.filter(candidate => candidate.key !== sectionKey),
  }));
}

/** Swap two adjacent entries of `items`; returns the same array reference when out of bounds. */
function swap<T>(items: T[], index: number, dir: -1 | 1): T[] {
  const target = index + dir;
  if (index < 0 || target < 0 || target >= items.length) return items;
  const next = [...items];
  [next[index], next[target]] = [next[target], next[index]];
  return next;
}

/** Reorder a tab one slot toward the start (`-1`) or end (`1`); no-op at the array boundary. */
export function moveTab(layout: EntityLayout, tabKey: string, dir: -1 | 1): EntityLayout {
  const index = layout.tabs.findIndex(tab => tab.key === tabKey);
  if (index < 0) return layout;
  const tabs = swap(layout.tabs, index, dir);
  return tabs === layout.tabs
    ? layout
    : {
      tabs,
    };
}

/** Reorder a section within its tab one slot toward the start (`-1`) or end (`1`); boundary no-op. */
export function moveSection(
  layout: EntityLayout,
  tabKey: string,
  sectionKey: string,
  dir: -1 | 1,
): EntityLayout {
  const tab = layout.tabs.find(candidate => candidate.key === tabKey);
  if (!tab) return layout;
  const index = tab.sections.findIndex(section => section.key === sectionKey);
  if (index < 0) return layout;
  const sections = swap(tab.sections, index, dir);
  if (sections === tab.sections) return layout;
  return mapTab(layout, tabKey, current => ({
    ...current,
    sections,
  }));
}
