import type { FastifyInstance } from "fastify";
import type { FetchMetadataResult } from "@eesimple/types";
import {
  checkUrl,
  extractDescription,
  extractTitle,
  fetchHeadHtml,
  fetchPageTitle,
} from "@/services/metadata";
import { lookupWebsiteByUrl, stripSiteNameSuffix } from "@/services/websites";
import { fetchYouTubeMetadata, isYouTubeVideoUrl } from "@/services/youtube";
import { channelKeyFromUrl, getYouTubeChannelByKey } from "@/services/youtubeChannels";
import { isValidUrl } from "@/utils/url";

const fetchTitleQuery = {
  type: "object",
  required: ["url"],
  additionalProperties: false,
  properties: {
    url: {
      type: "string",
      format: "uri",
    },
    siteName: {
      type: "string",
      minLength: 1,
    },
  },
} as const;

/** Metadata helpers (page-title lookup), mounted under `/api`. */
export async function metadataRoutes(app: FastifyInstance): Promise<void> {
  app.get("/api/fetch-title", {
    schema: {
      tags: ["metadata"],
      querystring: fetchTitleQuery,
    },
  }, async (req, reply) => {
    const {
      url, siteName: siteNameHint,
    } = req.query as { url: string;
      siteName?: string; };
    if (!isValidUrl(url)) {
      return reply.code(400).send({
        message: "url must be a valid http(s) URL",
      });
    }
    // YouTube watch pages rarely expose a parseable <title> before the </head> cutoff,
    // so use the same oEmbed lookup as /api/fetch-metadata before the strict HTML path.
    if (isYouTubeVideoUrl(url)) {
      const meta = await fetchYouTubeMetadata(url);
      // oEmbed titles are already clean (no site-name suffix to strip).
      if (meta?.title) {
        return {
          title: meta.title,
        };
      }
      // Fall through to the page-title fetch below if oEmbed had no title
      // (e.g. private/blocked video) — it can still 502 with a real reason.
    }
    const result = await fetchPageTitle(url);
    if (result.kind !== "ok") {
      let message: string;
      switch (result.kind) {
        case "timeout":
          message = "The request to that URL timed out. The site may be slow or unreachable.";
          break;
        case "http_error":
          message = `That URL returned an HTTP ${result.status} error and no title could be read.`;
          break;
        case "no_body":
          message = "The URL returned a response with no body — no title could be extracted.";
          break;
        case "no_title":
          message = "The page was fetched successfully but does not have a <title> tag.";
          break;
        case "network_error":
          message = "A network error occurred while trying to reach that URL.";
          break;
      }
      return reply.code(502).send({
        message,
        reason: result.kind,
      });
    }
    // Site names shouldn't be appended to autogenerated titles — strip a trailing
    // site-name/brand suffix (e.g. "Pricing · GitHub" → "Pricing").
    // A caller-supplied siteNameHint (for sites not yet in the DB) takes precedence.
    const {
      domain, website,
    } = await lookupWebsiteByUrl(url);
    return {
      title: stripSiteNameSuffix(result.title, {
        siteName: siteNameHint ?? website?.siteName,
        domain,
      }),
    };
  });

  // Lightweight reachability probe: does this URL still resolve? Never 502s — the client renders the
  // returned status/reason directly, so a dead link is a normal 200 result, not a request failure.
  app.get("/api/check-url", {
    schema: {
      tags: ["metadata"],
      querystring: fetchTitleQuery,
    },
  }, async (req, reply) => {
    const {
      url,
    } = req.query as { url: string };
    if (!isValidUrl(url)) {
      return reply.code(400).send({
        message: "url must be a valid http(s) URL",
      });
    }
    const result = await checkUrl(url);
    return {
      ok: result.kind === "ok",
      status: result.kind === "ok" || result.kind === "http_error" ? result.status : null,
      ...(result.kind !== "ok" && {
        reason: result.kind,
      }),
    };
  });

  // Richer metadata lookup: title for any URL, plus channel/duration/thumbnail for YouTube videos.
  // Unlike /api/fetch-title this never 502s — a partial result (e.g. title-only) is still useful.
  app.get("/api/fetch-metadata", {
    schema: {
      tags: ["metadata"],
      querystring: fetchTitleQuery,
    },
  }, async (req, reply): Promise<FetchMetadataResult> => {
    const {
      url, siteName: siteNameHint,
    } = req.query as { url: string;
      siteName?: string; };
    if (!isValidUrl(url)) {
      return reply.code(400).send({
        message: "url must be a valid http(s) URL",
      }) as unknown as FetchMetadataResult;
    }

    if (isYouTubeVideoUrl(url)) {
      const meta = await fetchYouTubeMetadata(url);
      // oEmbed titles are already clean; fall back to a page-title fetch if it was unavailable.
      let title = meta?.title ?? null;
      if (title === null) {
        const fallback = await fetchPageTitle(url);
        if (fallback.kind === "ok") title = fallback.title;
      }

      const channelKey = meta?.channelUrl ? channelKeyFromUrl(meta.channelUrl) : null;
      const existingChannel = channelKey ? await getYouTubeChannelByKey(channelKey) : null;
      const selfIds = existingChannel?.selfIds ?? [];

      // Strip channel self-identifier suffix from the title (e.g. " - SNL" from an SNL video).
      if (title && selfIds.length > 0) {
        for (const selfId of selfIds) {
          const stripped = stripSiteNameSuffix(title, {
            siteName: selfId,
          });
          if (stripped !== title) {
            title = stripped;
            break;
          }
        }
      }

      return {
        title,
        description: meta?.description ?? null,
        isYouTube: true,
        channel: meta?.channelName
          ? {
            name: meta.channelName,
            url: meta.channelUrl,
            key: channelKey,
            selfIds,
          }
          : null,
        durationSeconds: meta?.durationSeconds ?? null,
        thumbnailUrl: meta?.thumbnailUrl ?? null,
      };
    }

    const [html, { domain, website }] = await Promise.all([
      fetchHeadHtml(url),
      lookupWebsiteByUrl(url),
    ]);
    const rawTitle = html ? extractTitle(html) : null;
    return {
      title: rawTitle
        ? stripSiteNameSuffix(rawTitle, {
          siteName: siteNameHint ?? website?.siteName,
          domain,
        })
        : null,
      description: html ? extractDescription(html) : null,
      isYouTube: false,
      channel: null,
      durationSeconds: null,
      thumbnailUrl: null,
    };
  });
}
