import type { FastifyInstance } from "fastify";
import type { FetchMetadataResult } from "@eesimple/types";
import { fetchPageTitle } from "@/services/metadata";
import { lookupWebsiteByUrl, stripSiteNameSuffix } from "@/services/websites";
import { fetchYouTubeMetadata, isYouTubeVideoUrl } from "@/services/youtube";
import { isValidUrl } from "@/utils/url";

const fetchTitleQuery = {
  type: "object",
  required: ["url"],
  additionalProperties: false,
  properties: {
    url: {
      type: "string",
      format: "uri",
    },
    siteName: {
      type: "string",
      minLength: 1,
    },
  },
} as const;

/** Metadata helpers (page-title lookup), mounted under `/api`. */
export async function metadataRoutes(app: FastifyInstance): Promise<void> {
  app.get("/api/fetch-title", {
    schema: {
      tags: ["metadata"],
      querystring: fetchTitleQuery,
    },
  }, async (req, reply) => {
    const {
      url, siteName: siteNameHint,
    } = req.query as { url: string;
      siteName?: string; };
    if (!isValidUrl(url)) {
      return reply.code(400).send({
        message: "url must be a valid http(s) URL",
      });
    }
    const result = await fetchPageTitle(url);
    if (result.kind !== "ok") {
      let message: string;
      switch (result.kind) {
        case "timeout":
          message = "The request to that URL timed out. The site may be slow or unreachable.";
          break;
        case "http_error":
          message = `That URL returned an HTTP ${result.status} error and no title could be read.`;
          break;
        case "no_body":
          message = "The URL returned a response with no body — no title could be extracted.";
          break;
        case "no_title":
          message = "The page was fetched successfully but does not have a <title> tag.";
          break;
        case "network_error":
          message = "A network error occurred while trying to reach that URL.";
          break;
      }
      return reply.code(502).send({
        message,
        reason: result.kind,
      });
    }
    // Site names shouldn't be appended to autogenerated titles — strip a trailing
    // site-name/brand suffix (e.g. "Pricing · GitHub" → "Pricing").
    // A caller-supplied siteNameHint (for sites not yet in the DB) takes precedence.
    const {
      domain, website,
    } = await lookupWebsiteByUrl(url);
    return {
      title: stripSiteNameSuffix(result.title, {
        siteName: siteNameHint ?? website?.siteName,
        domain,
      }),
    };
  });

  // Richer metadata lookup: title for any URL, plus channel/duration/thumbnail for YouTube videos.
  // Unlike /api/fetch-title this never 502s — a partial result (e.g. title-only) is still useful.
  app.get("/api/fetch-metadata", {
    schema: {
      tags: ["metadata"],
      querystring: fetchTitleQuery,
    },
  }, async (req, reply): Promise<FetchMetadataResult> => {
    const {
      url, siteName: siteNameHint,
    } = req.query as { url: string;
      siteName?: string; };
    if (!isValidUrl(url)) {
      return reply.code(400).send({
        message: "url must be a valid http(s) URL",
      }) as unknown as FetchMetadataResult;
    }

    if (isYouTubeVideoUrl(url)) {
      const meta = await fetchYouTubeMetadata(url);
      // oEmbed titles are already clean; fall back to a page-title fetch if it was unavailable.
      let title = meta?.title ?? null;
      if (title === null) {
        const fallback = await fetchPageTitle(url);
        if (fallback.kind === "ok") title = fallback.title;
      }
      return {
        title,
        isYouTube: true,
        channel: meta?.channelName
          ? {
            name: meta.channelName,
            url: meta.channelUrl,
          }
          : null,
        durationSeconds: meta?.durationSeconds ?? null,
        thumbnailUrl: meta?.thumbnailUrl ?? null,
      };
    }

    const result = await fetchPageTitle(url);
    if (result.kind !== "ok") {
      return {
        title: null,
        isYouTube: false,
        channel: null,
        durationSeconds: null,
        thumbnailUrl: null,
      };
    }
    const {
      domain, website,
    } = await lookupWebsiteByUrl(url);
    return {
      title: stripSiteNameSuffix(result.title, {
        siteName: siteNameHint ?? website?.siteName,
        domain,
      }),
      isYouTube: false,
      channel: null,
      durationSeconds: null,
      thumbnailUrl: null,
    };
  });
}
